<?php
/** @var \App\Application\View\ViewHelper $view */
?>

<div class="row">
    <div class="col-lg-3">

    </div>
    <div class="col-lg-9">
        <section class="card card-primary">
            <header class="card-header">
                <div class="card-actions">
                    <?php if ($error) { ?>
                        <span class="badge badge-danger">
                            Neuloženo
                        </span>
                    <?php } ?>
                </div>
                <h2 class="card-title">
                    Upravit položku
                </h2>
            </header>
            <?= $view->include('election/admin/electionForm', [
                'formAction'    => $view->path('admin_election_edit', ['id' => $election['id']]),
                'election'      => $election,
                'error'         => $error ?? null,
                'title_options' => $title_options,
                'video_options' => $video_options,
            ]) ?>
        </section>
    </div>
</div>
