<?php
/*
 * @project polar
 * @author Rostislav Greipel
 * @link https://rogr.cz
 * @copyright (c) 2011 - 2021 ROGR All Rights Reserved
 * @license https://rogr.cz/license/eula EULA License
 */
?>

<div class="row">
    <div class="col-lg-6">
        <div class="row">
            <div class="col-sm">
                <section class="card card-featured-top card-featured-primary mb-4">
                    <div class="card-body">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-primary hvr-grow">
                                    <i class="fa fa-person-booth"></i>
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h4 class="title text-nowrap">
                                        Elections
                                    </h4>
                                    <div class="info text-nowrap">
                                        <strong class="amount">
                                            <?= $countElection ?? 0 ?>
                                        </strong>
                                        <span class="text-primary">
                                            celkem
                                        </span>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                    <a href="<?= $view->path('admin_election_list') ?>" class="text-muted text-uppercase">
                                        <i class="fa fa-fw fa-ellipsis-v"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <div class="col-sm">
                <section class="card card-featured-top card-featured-danger mb-4">
                    <div class="card-body">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-danger hvr-grow">
                                    <i class="fa fa-cogs"></i>
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h4 class="title text-nowrap">
                                        Settings
                                    </h4>
                                    <div class="info text-nowrap">
                                        <strong class="amount">

                                        </strong>
                                        <span class="text-danger">

                                        </span>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                    <a href="<?= $view->path('admin_election_setting') ?>" class="text-muted text-uppercase">
                                        <i class="fa fa-fw fa-ellipsis-v"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <section class="card mb-4">
            <header class="card-header">
                <div class="card-header-icon bg-primary">
                    <i class="fa fa-person-booth"></i>
                </div>
            </header>
            <div class="card-body text-center">
                <h3 class="font-weight-semibold mt-3 text-center">
                    Elections
                </h3>
                <p class="text-center">
                    TV Polar
                </p>
            </div>
        </section>
    </div>
</div>
