<?php
/*
 * @project polar
 * @author Rostislav Greipel
 * @link https://rogr.cz
 * @copyright (c) 2011 - 2021 ROGR All Rights Reserved
 * @license https://rogr.cz/license/eula EULA License
 */
?>

<div class="row">
    <div class="col-lg-3">

    </div>
    <div class="col-lg-9">
        <section class="card card-primary">
            <header class="card-header">
                <h2 class="card-title">
                    Nastavení
                </h2>
            </header>
            <div class="card-body">
                <p class="text-muted">Nastavení Elections modulu.</p>
            </div>
        </section>
    </div>
</div>
