<?php
/** @var \App\Application\View\ViewHelper $view */
$scheme = $scheme ?? 'dark';
$schemeOpposite = $scheme === 'dark' ? 'light' : 'dark';

$view->addHeadLink('<style>table tbody td.e {width: 1%; white-space: nowrap; text-align: left;} table tbody td.v {text-align: left;} html.dark table tr:hover {color: #cccccc;}</style>', 'style');

ob_start();
phpinfo();
$phpInfo = ob_get_clean();
$phpInfo = preg_replace('%^.*<body>(.*)</body>.*$%ms', '$1', $phpInfo);
$phpInfo = str_replace('<table>', '<table class="table table-hover mb-none text-color-' . $schemeOpposite . '">', $phpInfo);
?>

<div class="row">
    <div class="col-lg-12">
        <?= $phpInfo ?>
    </div>
</div>
