<div id="modalDanger" class="zoom-anim-dialog modal-block modal-full-color modal-block-danger mfp-hide">
    <section class="card">
        <header class="card-header">
            <a class="btn-close modal-dismiss pull-right" title="Zavřít">
                <i class="fa fa-fw fa-times"></i>
            </a>
            <h2 class="card-title">

            </h2>
        </header>
        <div class="card-body">
            <div class="modal-wrapper">
                <div class="modal-icon">
                    <i class="fa fa-times-circle"></i>
                </div>
                <div class="modal-text">
                    <h4>

                    </h4>
                    <p>

                    </p>
                </div>
            </div>
        </div>
        <footer class="card-footer">
            <div class="row">
                <div class="col-md-12 text-right">
                    <button class="btn btn-danger modal-confirm">
                        <i class="fa fa-fw fa-check"></i>
                        Potvrdit
                    </button>
                    <button class="btn btn-default modal-dismiss">
                        <i class="fa fa-fw fa-times"></i>
                        Zavřít
                    </button>
                </div>
            </div>
        </footer>
    </section>
</div>
