<div id="modalDanger" class="modal-block modal-block-danger mfp-hide">
    <section class="card">
        <header class="card-header">
            <h2 class="card-title"></h2>
        </header>
        <div class="card-body modal-text">
            <div class="modal-wrapper">
                <div class="modal-icon">
                    <i class="fa fa-times-circle"></i>
                </div>
                <div class="modal-text">
                    <h4></h4>
                    <p></p>
                </div>
            </div>
        </div>
        <footer class="card-footer">
            <div class="row">
                <div class="col-md-12 text-right">
                    <button class="btn btn-danger modal-confirm">Smazat</button>
                    <button class="btn btn-default modal-dismiss">Zrušit</button>
                </div>
            </div>
        </footer>
    </section>
</div>
