doctrine:
    dbal:
        default_connection: polar
        connections:
            polar:
                url: '%env(DATABASE_POLAR_URL)%'
            playkit:
                url: '%env(DATABASE_PLAYKIT_URL)%'
