job_list:
  path: /nabidka-prace
  controller: App\Job\Controller\Web\JobController::jobs

job_city_list:
  path: /nabidka-prace/{city_url}
  controller: App\Job\Controller\Web\JobController::city
  requirements:
    city_url: 'ostrava|karvina|frydek-mistek|opava|novy-jicin|bruntal'

job_our_detail:
  path: /nabidka-prace/doporucujeme/{job_id}/{job_url}
  controller: App\Job\Controller\Web\JobController::jobOur

job_city_detail:
  path: /nabidka-prace/{city_url}/{job_id}/{job_url}
  controller: App\Job\Controller\Web\JobController::job
  requirements:
    city_url: 'ostrava|karvina|frydek-mistek|opava|novy-jicin|bruntal'
