news:
  path: /zpravy
  controller: App\News\Controller\Web\NewsController::index

# shortlink
news_shortlink:
  path: /z/{shortlink}
  controller: App\News\Controller\Web\NewsController::shortlink
  requirements:
    shortlink: '[a-zA-Z0-9_-]+'

news_ticker:
  path: /zpravy/json/get-ticker
  controller: App\News\Controller\Web\NewsController::getTicker

news_crawl:
  path: /zpravy/json/get-crawl
  controller: App\News\Controller\Web\NewsController::getCrawl

news_online_content:
  path: /zpravy/json/get-content-online-news/{article_id}
  controller: App\News\Controller\Web\NewsController::getContentOnlineNews

news_guests:
  path: /hoste
  controller: App\News\Controller\Web\GuestController::guests

news_guests_guest:
  path: /hoste/{guest_id}/{guest_url}
  controller: App\News\Controller\Web\GuestController::guest

news_video_download:
  path: /zpravy/download/{video_id}/{quality}
  controller: App\News\Controller\Web\NewsController::download

news_overwrite_docx:
  path: /zpravy/overwrite-docx/{article_id}
  controller: App\News\Controller\Web\NewsController::overwriteDocx

news_pr:
  path: /zpravy/pr-clanky
  controller: App\News\Controller\Web\NewsController::prnews

news_pr_article:
  path: /zpravy/pr/{article_id}/{article_url}
  controller: App\News\Controller\Web\NewsController::articlePr

news_triptip:
  path: /kam-vyrazit
  controller: App\News\Controller\Web\TriptipController::index

news_triptip_get_triptip_list:
  path: /kam-vyrazit/json/get-triptip-list
  controller: App\News\Controller\Web\TriptipController::getTriptipList
  methods: POST

news_triptip_article:
  path: /kam-vyrazit/{url}/{city_url}/{article_id}/{article_url}
  controller: App\News\Controller\Web\TriptipController::article

# news_redactor musí být před news_region_city (obě mají 3 segmenty)
news_redactor:
  path: /zpravy/redaktor/{redactor_url}
  controller: App\News\Controller\Web\NewsController::redactor

news_region:
  path: /zpravy/{url}
  controller: App\News\Controller\Web\NewsController::region

news_region_city:
  path: /zpravy/{url}/{city_url}
  controller: App\News\Controller\Web\NewsController::city

news_region_city_article:
  path: /zpravy/{url}/{city_url}/{article_id}/{article_url}
  controller: App\News\Controller\Web\NewsController::article
