<?php
    /** @var \App\Application\View\ViewHelper $view */
    
    // Ticker + Crawl JS
    $view->addInlineScript(
    	    '// Ticker
            getTickerData();
            interval = startTicker();
            // Crawl
            getCrawlData();'
    	);

    function removeAccent(string $text, ?string $replace = null): string
    {
        $transliterator = Transliterator::createFromRules(':: Any-Latin; :: NFD; :: [:Nonspacing Mark:] Remove; :: NFC; :: [:Punctuation:] Remove; :: Lower();', Transliterator::FORWARD);
        $textTmp = $text;
        if ($transliterator) {
            $textTmp = $transliterator->transliterate($text);
            $textTmp = preg_replace('/[^a-z0-9]+/', '-', $textTmp);
            $textTmp = strtolower($textTmp);
            if ($replace) {
                $textTmp = str_replace(' ', $replace, $textTmp);
            }
        }

        return $textTmp;
    }

?>

<section class="page-header page-header-modern bg-color-light-scale-1 page-header-sm mb-0 mb-lg-4">
    <div class="container">
        <div class="row">
            <div class="col-md-4 d-flex align-items-center justify-content-end p-static order-2 d-none d-lg-block">
                <div class="text-dark pull-right">
                   (<?= $newsCount; ?> reportáží)
                </div>
            </div>
            <div class="col-md-8 align-self-center order-1">
                <ul class="breadcrumb d-block">
                    <li><a href="<?= $view->path('app_home') ?>">Domů</a></li>
                    <li class="active">Komerční sdělení</li>
                </ul>
            </div>
        </div>
    </div>
</section>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div id="crawl" class="mb-2 hide">
                <div id="crawlIcon">
                    Mimořádná zpráva:
                </div>
                <div class="crawl-container">
                    <div>
                        Načítám...
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-lg-7 mb-4 mb-lg-2">
            <div id="ticker" class="mb-4">
                <div id="tickerIcon" class="">
                    <!--<i class="fa fa-fw fa-info text-light"></i>-->
                </div>
                <div class="ticker-container">
                    <ul>
                        <div class="ticker-active">
                            <li>
                                <span>
                                    Načítám...
                                </span>
                            </li>
                        </div>
                    </ul>
                </div>
            </div>
            <?php if ($articles) {?>
                <div class="row">
                    <div class="col-12">
                        <?php $i = 0; ?>
                        <?php foreach ($articles as $item) { ?>
                            <?php
                                $item['article_url'] = removeAccent($item['title'], '-');
                                $today = new DateTime();
                                try {
                                    $date = new DateTime($item['public_from']);
                                    if ($today->format('Y-m-d') === $date->format('Y-m-d')) {
                                        $day = 'Dnes';
                                    } else {
                                        $yesterday = new DateTime();
                                        $yesterday->modify('-1 day');
                                        if ($yesterday->format('Y-m-d') === $date->format('Y-m-d')) {
                                            $day = 'Včera';
                                        } else {
                                            $day = (new IntlDateFormatter($locale, IntlDateFormatter::LONG, IntlDateFormatter::NONE))->format($date);
                                        }
                                    }
                                    $time = (new IntlDateFormatter($locale, IntlDateFormatter::NONE, IntlDateFormatter::SHORT))->format($date);
                                } catch (Exception $e) {
                                    $day = 'NaN';
                                    $time = 'NaN';
                                }
                            ?>

                            <div class="row mb-4-5">
                                <?php if (isset($item['picture'])) { ?>
                                    <div class="col-5 col-lg-6 pe-2 pe-md-3">
                                        <div class="">
                                            <a class="" href="<?= $view->path('news_pr_article', ['article_id' => $item['id'], 'article_url' => $item['article_url']]) ?>" title="<?= $item['title'] ?>">
                                                <span class="thumb-info thumb-info-lighten maxw-310">
                                                    <span class="thumb-info-wrapper">
                                                        <img src="<?= $item['picture'] ?>" class="img-fluid" alt="<?= $item['title'] ?>">
                                                        <?php if (strpos($item['picture'], '/videos/') !== false) { ?>
                                                            <span class="thumb-info-action">
                                                                <span class="thumb-info-action-icon">
                                                                    <i class="fas fa-play"></i>
                                                                    <span class="player_duration"><?= $item['duration'] ? gmdate("i:s", $item['duration']) : ''; ?></span>
                                                                </span>
                                                            </span>
                                                        <?php } ?>
                                                    </span>
                                                </span>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-7 col-lg-6 ps-1 pe-3">
                                        <h2 class="mb-1 mb-md-2">
                                            <a class="" href="<?= $view->path('news_pr_article', ['article_id' => $item['id'], 'article_url' => $item['article_url']]) ?>" title="<?= $item['title'] ?>">
                                                <?= $item['title'] ?>
                                            </a>
                                        </h2>
                                        <div class="text-1 text-tertiary line-height-7 mb-1">
                                            <span>
                                                <?= $day ?><!--
                                            --></span>,
                                            <span>
                                                <?= $time ?>
                                            </span>
                                        </div>
                                        <p class="block-truncate block-truncate-3 special-hidden-xs mb-0 line-height-6">
                                            <?= $item['anotation']; //mb_substr($item['anotation'], 0, 150, 'UTF-8') . ((mb_strlen($item['anotation'], 'UTF-8') > 150) ? '...' : '') ?>
                                            <!--<a href="<?php //= $view->path('news_pr_article', ['article_id' => $item['id'], 'article_url' => $item['article_url']]) ?>" title="<?php //= $item['title'] ?>">
                                                (celý článek)
                                            </a>-->
                                        </p>
                                    </div>
                                <?php } else { ?>
                                    <div class="col-12">
                                        <div class="">
                                            <h2 class="mb-1 mb-md-2">
                                                <a class="" href="<?= $view->path('news_pr_article', ['article_id' => $item['id'], 'article_url' => $item['article_url']]) ?>" title="<?= $item['title'] ?>">
                                                    <?= $item['title'] ?>
                                                </a>
                                            </h2>
                                            <div class="text-1 text-tertiary line-height-7 mb-1">
                                                <span>
                                                    <?= $day ?><!--
                                                --></span>,
                                                <span>
                                                    <?= $time ?>
                                                </span>
                                            </div>
                                            <p class="block-truncate block-truncate-3 special-hidden-xs mb-0 line-height-6">
                                                <?= $item['anotation']; //mb_substr($item['anotation'], 0, 150, 'UTF-8') . ((mb_strlen($item['anotation'], 'UTF-8') > 150) ? '...' : '') ?>
                                                <!--<a href="<?php //= $view->path('news_pr_article', ['article_id' => $item['id'], 'article_url' => $item['article_url']]) ?>" title="<?php //= $item['title'] ?>">
                                                    (celý článek)
                                                </a>-->
                                            </p>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>

                            <?php // REKLAMA PRO MOBILY (mezi 5. a 6. zprávou) ?>
                            <?php if ($i === 4) { ?>
                                <?= $view->include('banner/web/partial/ads/mobilesquare1', ['bannerMobilesquare1' => $bannerMobilesquare1 ?? null]) ?>
                            <?php } ?>

                            <?php $i++; ?>
                        <?php } ?>
                        <?= $view->include('application/pagination/paginator', ['route' => 'news_pr', 'routeParams' => [], 'page' => $page, 'total' => $total, 'limit' => $limit]) ?>

                        <?php // REKLAMA ?>
                        <?= $view->include('banner/web/partial/ads/article') ?>

                    </div>
                </div>
            <?php } ?>
        </div>
        <div class="col-12 col-lg-5">
            <?php // PR ?>
            <?= $view->include('news/partial/pr', ['pr' => $pr, 'bannerRectangle' => $bannerRectangle ?? null]) ?>
            <?php // REKLAMA ?>
            <br /><?= $view->include('banner/web/partial/ads/article-right-bottom') ?>
        </div>
    </div>
</div>
