<?php
/*
 * @project polar
 * @author Rostislav Greipel
 * @link https://rogr.cz
 * @copyright (c) 2011 - 2021 ROGR All Rights Reserved
 * @license https://rogr.cz/license/eula EULA License
 */

$view->setTitle('HD vysílání');
$view->addMeta('keywords', 'HD, vysílání, Polar, televize');
$view->addMeta('description', 'Nepřetržitý proud informací, zpráv a zábavných pořadů z vašeho okolí.');

if (isset($og)) {
    $view->addOgMeta('og:title', $og['title']);
    $view->addOgMeta('og:description', $og['description']);
    $view->addOgMeta('og:url', $og['url']);
    $view->addOgMeta('og:type', 'website');
    $view->addOgMeta('og:image', 'https://' . $_SERVER['SERVER_NAME'] . '/img/web/layout/microformat.png');
    $view->addOgMeta('og:image:secure_url', 'https://' . $_SERVER['SERVER_NAME'] . '/img/web/layout/microformat.png');
    $view->addOgMeta('og:image:width', '1920');
    $view->addOgMeta('og:image:height', '1080');
}

$view->setBreadcrumbs([
    ['label' => 'Domů', 'url' => $view->path('app_home')],
    ['label' => 'HD vysílání'],
]);

$view->addBodyScript($view->asset('vendor/web/moment/js/moment.min.js'));

$view->addHeadLink('stylesheet', $view->asset('vendor/web/video-js/video-js.min.css'));
$view->addHeadLink('stylesheet', $view->asset('vendor/web/video-js/theme/custom/index.css?ver=11'));
$view->addHeadLink('stylesheet', $view->asset('vendor/web/nanoscroller/css/nanoscroller.min.css'));

$view->addBodyScript($view->asset('vendor/web/video-js/video.min.js'));
$view->addBodyScript($view->asset('vendor/web/video-js/lang/cs.js'));
$view->addBodyScript($view->asset('vendor/web/nanoscroller/js/nanoscroller.min.js'));

// Ticker + Crawl JS
$view->addInlineScript(
    'moment.locale("cs");
    // Ticker
    getTickerData();
    interval = startTicker();
    // Crawl
    getCrawlData();'
);

// Program
$view->addInlineScript(
    'window.addEventListener("load", function () {
        getProgram();
        function getProgram() {
            $.post("' . $view->path('app_get_program_for_hd') . '",
                {},
                function(json) {
                    $("#programHd").html(json.content);
                    $(".nano").nanoScroller({ alwaysVisible: true });
                    if (json.reload) {
                        setTimeout(() => {
                            getProgram();
                        }, json.reload * 1000);
                    }
                }, 
                "json"      
            );
        }
        $(".showProgram").click(function(e){
            let id = $(this).attr("id");
            id = id.substr(id.length - 1);
            $(".showProgram").removeClass("btn-primary").addClass("btn-default");
            $(this).addClass("btn-primary");
            $("#programHd .nano").addClass("hide");
            $("#programHd #program-" + id).removeClass("hide");
            $(".nano").nanoScroller({ alwaysVisible: true });
        });
    });'
);

// Player VideoJS
$view->addInlineScript(
    '
    let player = videojs("player", {
        controlBar: {
            children: {
                playToggle: true,
                LiveDisplay: true,
                volumePanel: {
                    inline: true
                },
                fullscreenToggle: true
            }
        }
    });
    '
);
?>

<section class="page-header page-header-modern bg-color-light-scale-1 page-header-sm mb-0 mb-lg-4">
    <div class="container">
        <div class="row">
            <div class="col-md-12 align-self-center order-1">
                <?= $view->include('application/navigation/breadcrumb') ?>
            </div>
        </div>
    </div>
</section>

<div class="container mb-4">
    <div class="row">
        <div class="col-md-12">
            <div id="crawl" class="mb-2 hide">
                <div id="crawlIcon">
                    Mimořádná zpráva:
                </div>
                <div class="crawl-container">
                    <div>
                        Načítám...
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-lg-8 mb-4 mb-lg-2">
            <div id="ticker" class="mb-0">
                <div id="tickerIcon" class="">
                    <!--<i class="fa fa-fw fa-info text-light"></i>-->
                </div>
                <div class="ticker-container">
                    <ul>
                        <div class="ticker-active">
                            <li>
                                <span>
                                    Načítám...
                                </span>
                            </li>
                        </div>
                    </ul>>
                </div>
            </div>

            <video id="player" class="video-js vjs-fluid vjs-16-9 vjs-theme-fantasy mt-4 mt-lg-0" data-setup='{"controls": true, "autoplay": false, "preload": "auto", "poster": "/img/web/poster-hd.jpg" }'>
                <source src="https://stream.polar.cz:443/polar/polarlive-1/playlist.m3u8" type="application/x-mpegURL">
                <p class="vjs-no-js">
                    Váš prohlížeč nepodporuje HTML5 video. Zde je odkaz na <a href="https://stream.polar.cz:443/polar/polarlive-2/playlist.m3u8">stream</a>.
                </p>
            </video>
        </div>
        <div id="programContainer" class="col-12 col-lg-4 match-height">
            <div class="row mt-0 mb-3">
                <div class="col-7 d-flex align-items-center">
                    <button id="programday1" class="showProgram btn btn-primary btn-xs me-2">
                        Dnes
                    </button>
                    <button id="programday2" class="showProgram btn btn-default btn-xs me-2">
                        Zítra
                    </button>
                    <button id="programday3" class="showProgram btn btn-default btn-xs">
                        Pozítří
                    </button>
                </div>
                <div class="col-5 d-flex align-items-center justify-content-end">
                    <a class="text-2" href="/tv-program" title="TV program"> <!-- TODO: až bude route pro TV program, nahradit za $view->path('app_program') -->
                        celý TV program
                        <i class="fas fa-chevron-right text-1"></i>
                    </a>
                </div>
            </div>
            <div id="programHd">

            </div>
        </div>
    </div>
</div>
