<?php
/** @var \App\Application\View\ViewHelper $view */

$view->setTitle('Mapa stránek');
$view->addMeta('keywords', 'mapa stránek');
$view->addMeta('description', 'Mapa stránek');

$view->setBreadcrumbs([
    ['label' => 'Domů', 'url' => $view->path('app_home')],
    ['label' => 'Mapa stránek'],
]);
?>

<section class="page-header page-header-modern bg-color-light-scale-1 page-header-sm mb-0 mb-lg-4">
    <div class="container">
        <div class="row">
            <div class="col-md-12 align-self-center order-1">
                <?= $view->include('application/navigation/breadcrumb') ?>
            </div>
        </div>
    </div>
</section>
<br />
<div class="container py-2">
    <div class="row justify-content-between">
        <div class="col-lg-6">
            <?php
            $nav = require dirname(__DIR__, 3) . '/config/navigation.php';
            $newsNav = $nav['regions'];
            ?>
            <ul class="nav nav-list flex-column mb-5">
                <li class="nav-item"><a class="nav-link" href="<?= $view->path('app_home') ?>" title="Domů"><i class="fa fa-fw fa-home mr-1" aria-hidden="true"></i><img src="/img/web/layout/header/home.svg" alt=""></a></li>
                <?php foreach ($newsNav as $region) { ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $region['url'] ?>" title="<?= $region['label'] ?>"><?= $region['label'] ?></a>
                        <?php if (!empty($region['cities'])) { ?>
                        <ul>
                            <?php foreach ($region['cities'] as $city) { ?>
                            <li class="nav-item"><a class="nav-link" href="<?= $city['url'] ?>" title="<?= $city['label'] ?>"><?= $city['label'] ?></a></li>
                            <?php } ?>
                        </ul>
                        <?php } ?>
                    </li>
                <?php } ?>
                <li class="nav-item"><a class="nav-link" href="<?= $view->path('app_sitemap') ?>" title="Sitemap">Sitemap</a></li>
                <li class="nav-item"><a class="nav-link" href="<?= $view->path('app_sitemap_xml') ?>" title="sitemap.xml">sitemap.xml</a></li>
                <li class="nav-item"><a class="nav-link" href="<?= $view->path('app_robots_txt') ?>" title="robots.txt">robots.txt</a></li>
            </ul>
        </div>
        <div class="col-lg-6">
            <h2><?= 'Ostatní' ?></h2>
            <ul class="list-unstyled">
                <?php foreach ($nav['footer'] as $item) { ?>
                    <li><a href="<?= $item['url'] ?>"<?= !empty($item['target']) ? ' target="' . $item['target'] . '"' : '' ?>><?= $item['label'] ?></a></li>
                <?php } ?>
            </ul>
        </div>
    </div>
</div>
