<?php
/** @var \App\Application\View\ViewHelper $view */

$view->addHeadLink('stylesheet', $view->asset('vendor/admin/file-upload/css/file-upload.css'));

$view->addBodyScript($view->asset('vendor/admin/file-upload/js/ui-widget.js'));
$view->addBodyScript($view->asset('vendor/admin/file-upload/js/iframe-transport.js'));
$view->addBodyScript($view->asset('vendor/admin/file-upload/js/file-upload.js'));

// Nahrání obrázku
$view->addInlineScript(
    '$("#fileupload").fileupload({
        formData: {
            show_id: null
        },
        dropZone: "#image",
        dataType: "json",
        add: function (e, data) {
            $("#image .progress").removeClass("d-none");
            $("#image .progress .progress-bar").css("width", "0%");
            data.submit();
        },
        progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $("#image .progress .progress-bar").css("width", progress + "%");
        },
        done: function (e, data) {
            $("#image .progress .progress-bar").removeClass("progress-bar-striped progress-bar-animated active");
            $("#image .progress").addClass("d-none");
            $("#image .image-outer-container img").attr("src", "/" + data.result.url);
            $("input[name=image]").val(data.result.url);
            if (data.result.error) {
                new PNotify({
                    title: "Obrázek pořadu",
                    text: data.result.error,
                    type: "error"
                });
            } else {
                new PNotify({
                    title: "Obrázek pořadu",
                    text: "Obrázek pořadu byl úspěšně nahrán",
                    type: "success"
                });
            }
        },
        fail: function (e, data) {
            $("#image .progress .progress-bar").removeClass("progress-bar-striped progress-bar-animated active");
            $("#image .progress").addClass("d-none");
            new PNotify({
                title: "Obrázek pořadu",
                text: "Obrázek pořadu se nepodařilo nahrát",
                type: "error"
            });
        }
    });'
);

// Nahrání obrázku (klik na ikonu)
$view->addInlineScript(
    '$("#image .image-outer-container .image-inner-container .image-button").click(function(e){
        $("#fileupload").click();
    });'
);
?>

<div class="row">
    <div class="col-lg-3">
        <div id="image">
            <h3 class="mt-0">
                Obrázek
                <small class="pull-right text-muted">
                    (<?= $setting['show_img_width'] ?>px x <?= $setting['show_img_height'] ?>px)
                </small>
            </h3>
            <div class="mb-4">
                <div class="image-outer-container d-inline-flex">
                    <div class="image-inner-container bg-primary">
                        <img class="img-fluid border-color-<?= $scheme ?>" src="<?= $view->asset('data/mimoradne/show/!default-show.png') . '?ver=' . date('YmdHis') ?>" alt="">
                        <span class="image-button bg-<?= $schemeOpposite ?>">
                            <i class="fa fa-camera text-color-<?= $scheme ?>"></i>
                        </span>
                    </div>
                    <input id="fileupload" class="image-input" type="file" name="file" data-url="<?= $view->path('admin_program_showex_json_upload_image') ?>" accept="image/*">
                </div>
            </div>
            <div class="progress mb-3 d-none">
                <div class="progress-bar progress-bar-primary" role="progressbar" style="width: 0">
                    <span class="sr-only">0%</span>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-9">
        <section class="card card-primary">
            <header class="card-header">
                <div class="card-actions">
                    <span id="msgNotSaved" class="badge badge-danger d-none">
                        Neuloženo
                    </span>
                </div>
                <h2 class="card-title">
                    Přidat mimořádný pořad
                </h2>
            </header>
            <?= $view->include('program/admin/showex/showexForm', [
                'setting' => $setting,
                'categories' => $categories,
                'show' => null,
                'show_id' => null,
            ]) ?>
        </section>
    </div>
</div>
