<?php

/** @var \App\Application\View\ViewHelper $view */

// HeadTitle
$view->setTitle('Volby 2025');

// HeadMeta
$view->addMeta('description', 'Která politická strana získá Vaše sympatie? TV Polar Vám představí jednotlivé volební programy a kandidátní listiny politických stran pro parlamentní volby 2025 Moravskoslezského kraje. Pojďme k volbám, je to náš kraj!');
$view->addMeta('keywords', 'volby 2025, parlamentní volby, politická strana, volební program, kandidátní listina');

// META pro Facebook
$currentUrl = $currentUrl ?? '';
$view->addOgMeta('og:title', 'Volby | Televize POLAR');
$view->addOgMeta('og:description', 'Která politická strana získá Vaše sympatie? TV Polar Vám představí jednotlivé volební programy a kandidátní listiny politických stran pro parlamentní volby 2025 Moravskoslezského kraje. Pojďme k volbám, je to náš kraj!');
$view->addOgMeta('og:url', $currentUrl);
$view->addOgMeta('og:type', 'website');
$view->addOgMeta('og:site_name', 'polar.cz');
$view->addOgMeta('og:image', '/img/web/volby/microformat_2025.png');
$view->addOgMeta('og:image:secure_url', '/img/web/volby/microformat_2025.png');
$view->addOgMeta('og:image:width', '1920');
$view->addOgMeta('og:image:height', '1080');

$view->setBreadcrumbs([
    ['label' => 'Volby 2025', 'url' => $view->path('election_2025')],
]);

$view->addHeadLink('stylesheet', $view->asset('vendor/web/video-js/video-js.min.css'));
$view->addHeadLink('stylesheet', $view->asset('vendor/web/video-js/theme/custom/index.css?ver=11'));

$view->addBodyScript($view->asset('vendor/web/video-js/video.min.js'));
$view->addBodyScript($view->asset('vendor/web/video-js/lang/cs.js'));

$view->addInlineScript(
    '// Ticker
    getTickerData();
    interval = startTicker();
    // Crawl
    getCrawlData();'
);

// Player VideoJS
$view->addInlineScript(
    '
    if ($(window).width() > 992) {
        let playerLiveSDHD = videojs("playerLiveSDHD", {
            controls: true, 
            autoplay: false, 
            preload: "none", 
            aspectRatio: "16:9", 
            muted: true, 
            inactivityTimeout: 1000,
            controlBar: {
                children: {
                    playToggle: true,
                    LiveDisplay: true,
                    volumePanel: {
                        inline: true
                    },
                    fullscreenToggle: true
                }
            }
        });
    }
    '
);

// Volební menu
$view->addInlineScript(
    '		
    // Přidání třídy "open", aby správně fungovalo podbarvování položek v rámci menu/submenu
	$(".elections_menu nav > ul.nav-pills").on("click", "li:not(.open) > a", function(){
		$(this).parent().addClass("open");
	});
	$(".elections_menu nav > ul.nav-pills").on("click", "li.open > a", function(){
		$(this).parent().removeClass("open");
	});
 
 	// Napodobení hlavního menu - při hover vždy červená pouze jedna položka menu
    $(".elections_menu nav ul.nav-pills li a:not(.active)").hover(function(){
		$(".elections_menu nav > ul.nav-pills > li > a.nav-link.active").css("background-color", "#0f375a");
	}, function(){
		$(".elections_menu nav > ul.nav-pills > li > a.nav-link.active").css("background-color", "#900");
	});
    '
);

/**
 * @param string $text
 * @param string|null $replace
 * @return string
 */
function removeAccent($text, $replace = null): string
{
    $transliterator = Transliterator::createFromRules(':: Any-Latin; :: NFD; :: [:Nonspacing Mark:] Remove; :: NFC; :: [:Punctuation:] Remove; :: Lower();', Transliterator::FORWARD);
    if ($transliterator) {
        $text = $transliterator->transliterate($text);
    }
    $text = preg_replace('/\p{C}+/u', '', $text);
    if ($replace) {
        $text = str_replace(' ', $replace, $text);
    }
    return $text;
}

?>

<section class="page-header page-header-modern bg-color-light-scale-1 page-header-sm mb-0 mb-lg-4">
    <div class="container">
        <div class="row">
            <div class="col-md-12 align-self-center order-1">
                <?= $view->include('application/navigation/breadcrumb') ?>
            </div>
        </div>
    </div>
</section>

<div class="container">
    <div class="row">
        <div class="col-12">
            <div id="crawl" class="mb-2 hide">
                <div id="crawlIcon">
                    Mimořádná zpráva:
                </div>
                <div class="crawl-container">
                    <div>
                        Načítám...
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div id="ticker" class="mb-3">
                <div id="tickerIcon" class="">
                    <!--<i class="fa fa-fw fa-info text-light"></i>-->
                </div>
                <div class="ticker-container">
                    <ul>
                        <div class="ticker-active">
                            <li>
                                <span>
                                    Načítám...
                                </span>
                            </li>
                        </div>
                    </ul>>
                </div>
            </div>

            <div class="row justify-content-center mb-2-3">
                <div class="col-8 col-md-4 col-lg-3 mb-2-3 px-0">
                    <a href="<?= $view->path('election_2025') ?>" title="Krajské volby 2025">
                        <img src="/img/web/volby/volby_2025_logo.png" alt="Volby 2025" class="img-fluid">
                    </a>
                </div>
                <div class="col-12 text-center">
					<h2 class="text-secondary text-4-5 font-weight-normal">Volby do Poslanecké sněmovny <span class="text-nowrap">3. a 4. října 2025</span> - Moravskoslezský kraj</h2>
                </div>
            </div>

			<div class="row mb-4-5 elections_menu y2025">
				<div class="col-12">
					<?= $view->include('election/web2025/partial/menu', ['active' => 'index']) ?>
				</div>
			</div>
		</div>
	</div>

	<div class="row sticky-square">
        <div class="col-lg-7">
			<!-- Volební zprávy -->
			<?php if ($articles) { ?>
				<h2 class="text-primary mb-4 d-none">Volební zpravodajství</h2>
                <?php foreach ($articles as $key => $item) { ?>

                    <?php
					if ($item['region_url'] && $item['city_url']) {
						$region_city_url = $view->path('news_region_city', ['url' => $item['region_url'], 'city_url' => $item['city_url']]);
						if ($item['city_url'] === 'cely-ms-kraj') {
							$region_city_url = $view->path('news');
						}
					}

					try {
						$today = new DateTime();
						$dateUpdate = new DateTime($item['updated_date']);
						if ($today->format('Y-m-d') === $dateUpdate->format('Y-m-d')) {
							$dayUpdate = 'Dnes';
						} else {
							$yesterday = new DateTime();
							$yesterday->modify('-1 day');
							if ($yesterday->format('Y-m-d') === $dateUpdate->format('Y-m-d')) {
								$dayUpdate = 'Včera';
							} else {
								$dayUpdate = $view->dateFormat($dateUpdate, IntlDateFormatter::LONG, IntlDateFormatter::NONE, $locale);
							}
						}
						$timeUpdate = $view->dateFormat($dateUpdate, IntlDateFormatter::NONE, IntlDateFormatter::SHORT, $locale);

						$today = new DateTime();
						$date = new DateTime($item['public_from']);
						if ($today->format('Y-m-d') === $date->format('Y-m-d')) {
							if ($item['label']) {
								$day = 'dnes';
							} else {
								$day = 'Dnes';
							}
						} else {
							$yesterday = new DateTime();
							$yesterday->modify('-1 day');
							if ($yesterday->format('Y-m-d') === $date->format('Y-m-d')) {
								if ($item['label']) {
									$day = 'včera';
								} else {
									$day = 'Včera';
								}
							} else {
								$day = $view->dateFormat($date, IntlDateFormatter::LONG, IntlDateFormatter::NONE, $locale);
							}
						}
						$time = $view->dateFormat($date, IntlDateFormatter::NONE, IntlDateFormatter::SHORT, $locale);
					} catch (Exception $e) {
						$day = 'NaN';
						$time = 'NaN';
						$dayUpdate = 'NaN';
						$timeUpdate = 'NaN';
					}
				?>

                    <div class="row mb-4-5">
					<?php if ($item['picture']) { ?>
						<div class="col-5 col-lg-6 pe-2 pe-md-3">
							<div class="">
								<a class="" href="<?= $view->path('news_region_city_article', ['url' => $item['region_url'], 'city_url' => $item['city_url'], 'article_id' => $item['article_id'], 'article_url' => $item['article_url']]) ?>" title="<?= $item['title'] ?>">
									<span class="thumb-info thumb-info-lighten">
										<span class="thumb-info-wrapper">
											<img src="<?= $item['picture'] ?>" class="img-fluid" alt="<?= $item['title'] ?>">
											<?php if (strpos($item['picture'], '/videos/') !== false) { ?>
												<span class="thumb-info-action">
													<span class="thumb-info-action-icon">
														<i class="fas fa-play"></i>
														<span class="player_duration"><?= $item['duration'] ? gmdate("i:s", $item['duration']) : ''; ?></span>
													</span>
												</span>
											<?php } ?>
										</span>
									</span>
								</a>
							</div>
						</div>
						<div class="col-7 col-lg-6 ps-1 pe-3">
							<h2 class="mb-1 mb-md-2">
								<a class="" href="<?= $view->path('news_region_city_article', ['url' => $item['region_url'], 'city_url' => $item['city_url'], 'article_id' => $item['article_id'], 'article_url' => $item['article_url']]) ?>" title="<?= $item['title'] ?>">
									<?= $item['title'] ?>
								</a>
							</h2>
							<div class="text-1 text-tertiary line-height-7 mb-1">
								<?php
									$now_minus_x = new DateTime();
									$now_minus_x = $now_minus_x->modify('-' . $HOURS_DELETE_LABELS . ' hours')->format('Y-m-d H:i:s');
									if ($item['label'] && $item['updated_date'] > $now_minus_x) {
										echo $item['label'];
										echo ' <span>' . $dayUpdate . '</span> <span>' . $timeUpdate . '</span>, <span>vydáno ' . $day . '</span> <span>' . $time . '</span>&nbsp;|';
									} else {
										echo '<span>' . $day . '</span> <span>' . $time . '</span>&nbsp;|';
									}
								?>
								<span>
									<a href="<?= $region_city_url ?>" title="<?= $item['city_title'] ?>"><?= $item['city_title'] ?></a>&nbsp;|
								</span>
								<span>
									<?= '<a class="" href="' . $view->path('news_redactor', ['redactor_url' => $item['author_url']]) . '" title="' . $item['author'] . '">' . $item['author'] . '</a>'; ?><!--
								--></span><!--
								--><span><!--
									--><?= $item['show_id'] ? '&nbsp;| <a class="" href="' . $view->path('program_show_' . $item['show_id']) . '" title="' . ($shows[$item['show_id']] ?? '') . '">' . ($shows[$item['show_id']] ?? '') . '</a>' : ''; ?>
								</span>
							</div>
							<p class="block-truncate block-truncate-3 special-hidden-xs mb-0 line-height-6">
								<?= $item['anotation']; ?>
							</p>
						</div>
					<?php } else { ?>
						<div class="col-12">
							<div class="">
								<h2 class="mb-1 mb-md-2">
									<a class="" href="<?= $view->path('news_region_city_article', ['url' => $item['region_url'], 'city_url' => $item['city_url'], 'article_id' => $item['article_id'], 'article_url' => $item['article_url']]) ?>" title="<?= $item['title'] ?>">
										<?= $item['title'] ?>
									</a>
								</h2>
								<div class="text-1 text-tertiary line-height-7 mb-1">
									<?php
										$now_minus_x = new DateTime();
										$now_minus_x = $now_minus_x->modify('-' . $HOURS_DELETE_LABELS . ' hours')->format('Y-m-d H:i:s');
										if ($item['label'] && $item['updated_date'] > $now_minus_x) {
											echo $item['label'];
											echo ' <span>' . $dayUpdate . '</span> <span>' . $timeUpdate . '</span>, <span>vydáno ' . $day . '</span> <span>' . $time . '</span>&nbsp;|';
										} else {
											echo '<span>' . $day . '</span> <span>' . $time . '</span>&nbsp;|';
										}
									?>
									<span>
										<a href="<?= $region_city_url ?>" title="<?= $item['city_title'] ?>"><?= $item['city_title'] ?></a>&nbsp;|
									</span>
									<span>
										<?= '<a class="" href="' . $view->path('news_redactor', ['redactor_url' => $item['author_url']]) . '" title="' . $item['author'] . '">' . $item['author'] . '</a>'; ?><!--
									--></span><!--
									--><span><!--
										--><?= $item['show_id'] ? '&nbsp;| <a class="" href="' . $view->path('program_show_' . $item['show_id']) . '" title="' . ($shows[$item['show_id']] ?? '') . '">' . ($shows[$item['show_id']] ?? '') . '</a>' : ''; ?>
									</span>
								</div>
								<p class="block-truncate block-truncate-3 special-hidden-xs mb-0 line-height-6">
									<?= $item['anotation']; ?>
								</p>
							</div>
						</div>
					<?php } ?>
					</div>
                <?php } ?>
				<div class="row">
					<div class="col-12">
						<?= $view->include('application/pagination/paginator', ['route' => 'election_2025', 'routeParams' => [], 'page' => $page, 'total' => $total, 'limit' => $limit]) ?>
					</div>
				</div>
			<?php } ?>
			<!-- END Volební zprávy -->

		</div>

        <div class="col-lg-5">
			<?php if ($elections) { ?>
				<h2 class="text-primary mb-4">Volební studia</h2>
				<div class="row row-cols-1 row-cols-md-2 mb-3">
					<?php foreach ($elections as $key => $value) { ?>
						<div class="col mb-4-5">
							<a class="" href="<?= $view->path('election_2025_detail', ['kstrana' => $value['KSTRANA'], 'strana_url' => removeAccent($value['NAZEV_STRK'], '-')]) ?>" title="<?= $value['title'];?>">
								<span class="thumb-info thumb-info-lighten mb-2">
									<span class="thumb-info-wrapper">
										<?php
											if (file_exists($PUBLIC_PATH . '/data/program/thumbs/' . $value['name'] . '.jpg')) {
												$image = '/data/program/thumbs/' . $value['name'] . '.jpg';
											} else {
												$image = '/data/program/show/!default-show.png';
											}
										?>
										<img src="<?= $image ?>" class="img-fluid" alt="<?= $value['title'] ?>">
										<span class="thumb-info-action">
											<span class="thumb-info-action-icon">
												<i class="fas fa-play"></i>
												<span class="player_duration"><?= $value['duration'] ? gmdate("i:s", $value['duration']) : ''; ?></span>
											</span>
										</span>
									</span>
								</span>
							</a>
							<a class="" href="<?= $view->path('election_2025_detail', ['kstrana' => $value['KSTRANA'], 'strana_url' => removeAccent($value['NAZEV_STRK'], '-')]) ?>" title="<?= $value['title'] ?>">
								<h4 class="text-4 text-secondary mb-0"><?= $value['title']; ?></h4>
							</a>
							<div class="line-height-6"><?= $value['description']; ?></div>
						</div>
					<?php } ?>
				</div>
			<?php } ?>

			<?php if (!$elections) { ?>
				<div class="row">
					<?php $k = 0; ?>
					<div class="col-12 p-relative">
						<aside class="section-best-news" data-plugin-sticky data-plugin-options="{'minWidth': 991, 'containerSelector': '.sticky-square', 'padding': {'top': 63}}">
							<div class="row mb-5">
								<div class="col-12">
									<?php if ($psrkl) { ?>
										<h2 class="text-primary mb-3">Seznam kandidátů</h2>
										<div class="row">
											<?php foreach ($psrkl as $value) { ?>
												<div class="col-6">
													<a href="<?= $view->path('election_2025_detail', ['kstrana' => $value['KSTRANA'], 'strana_url' => removeAccent($value['NAZEV_STRK'], '-')]) ?>" title="<?= $value['NAZEVCELK'];?>">
														<?= '<b>'.$value['ZKRATKAK8'].'</b><br />'; ?>
													</a>
												</div>
											<?php } ?>
										</div>
									<?php } ?>
								</div>
							</div>
							<!-- Živé vysílání + počasí -->
							<div class="row d-none d-lg-flex mb-4">
								<div class="col-8">
									<div id="video-container" class="ratio ratio-16x9">
										<video id="playerLiveSDHD" class="video-js vjs-fluid vjs-16-9 vjs-theme-fantasy" style="position:absolute;top:0;left:0;overflow:hidden;" height="100%" width="100%" poster="/img/web/poster-hd.png">
											<source src="https://stream.polar.cz:443/polar/polarlive-2/playlist.m3u8" type="application/x-mpegURL">
											<p class="vjs-no-js">
												Váš prohlížeč nepodporuje HTML5 video. Zde je odkaz na <a href="https://stream.polar.cz:443/polar/polarlive-2/playlist.m3u8">stream</a>.
											</p>
										</video>
									</div>
								</div>
								<div class="col-4">
									<?php if ($weather) { ?>
										<h3 class="text-primary text-3-4 mb-4">Počasí - <?= $weather_region; ?></h3>
										<?php $days = ['Dnes', 'Zítra', 'Pozítří']; $m = 0; ?>
										<?php foreach ($weather as $weather_item) { ?>
											<div class="row text-secondary text-3-4 mb-2">
												<div class="col-5">
													<?= isset($days[$m]) ? $days[$m] : ''; ?>
												</div>
												<div class="col-3 px-2">
													<img src="<?= $view->asset('/img/web/weather/' . $weather_item['status'] . '.png') ?>" class="img-fluid" alt="" />
												</div>
												<div class="col-4">
													<?= $weather_item['temperature_day']; ?>°C
												</div>
											</div>
											<?php $m++; ?>
										<?php } ?>
									<?php } ?>
								</div>
							</div>
							<!-- END Živé vysílání + počasí -->

							<?php // REKLAMA ?>
							<!-- reklama nad PR -->
							<?= $view->include('banner/web/partial/ads/article-right-top', ['bannerRectangle' => $bannerRectangle ?? null]) ?>

							<!-- PR články -->
							<?php $pr_block = []; ?>
							<?php if (isset($pr[$k])) {$pr_block[] = $pr[$k];} if (isset($pr[$k+1])) {$pr_block[] = $pr[$k+1];} ?>
							<?= $view->include('news/partial/pr-block', ['pr_block' => $pr_block]) ?>
							<?php $k = $k + 2; ?>
							<br />
							<?php // REKLAMA ?>
							<!-- reklama pod PR -->
							<?= $view->include('banner/web/partial/ads/article-right-bottom', ['bannerSquare' => $bannerSquare ?? null]) ?>
							<br class="d-none d-lg-inline" />
						</aside>
					</div>
				</div>
			<?php } ?>

        </div>
	</div>
</div>
