<?php
/** @var \App\Application\View\ViewHelper $view */
?>
<!DOCTYPE html>
<html lang="cs">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="application-name" content="<?= $feed['description'];?>">
		<meta name="author" content="Rostislav Greipel">
		<meta name="robots" content="index,follow">
		<meta name="googlebot" content="index,follow">
		<title>RSS</title>
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&subset=latin,latin-ext&font-display=swap">
		<link rel="stylesheet" href="<?= $view->asset('vendor/web/rss-readers/bootstrap/bootstrap.min.css?ver=0.1');?>">
		<style>
            .container {margin: 0;}
            #bruntalTab {max-width: 768px;}
            .date {color: #666; text-shadow: none; font-size: 11px; margin-top: 5px;}
            body {background-color: #1E1E1E; font-family: Arial, sans-serif;}
            .nav-pills>li>a {border-radius: 50% 50%;}
            .nav>li>a {font-size: 22px; font-weight: 500; color: #fff; display: inline-block; padding: 2px 12px;}
            .nav>li>a:hover, 
            .nav>li>a:focus, 
            .nav-pills>li.active>a, 
            .nav-pills>li.active>a:hover, 
            .nav-pills>li.active>a:focus {text-decoration: none; color: #000; background-color: #F8C10F; outline: none;}
            .title-section {margin-top: 20px; margin-bottom: 20px; padding-left: 30px; max-width: 100%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: #fff;}
            .title-section a {font-size: 24px; color: #fff; text-decoration: none; border-bottom: 2px solid #565656; padding-bottom: 2px; line-height: 34px;}
            .title-section a:hover {border-bottom: 2px solid #fff;}
            .date {color: #fff; font-size: 16px; margin-top: 0px; padding-left: 30px;}
            .col-tab {padding: 0 0 0 3px;}
            .col-nav {padding: 15px 1px 0 1px}
            .nav-stacked>li+li, .nav>li {margin-left: 2px;}
            @media screen and (max-width: 480px) {
                .nav>li>a {font-size: 12px; padding: 2px 7px;} 
                .title-section a {font-size: 20px;}
                .title-section {margin-top: 10px; margin-bottom: 15px; padding-left: 10px;}
                .date {padding-left: 10px;}
            }
        </style>
		<script src="<?= $view->asset('vendor/web/rss-readers/jquery/jquery.min.js?ver=0.1');?>"></script>
		<script src="<?= $view->asset('vendor/web/rss-readers/bootstrap/bootstrap.min.js?ver=0.1');?>"></script>
		<script>
            var tabCarousel = setInterval(function() {
                var tabs = $("#bruntalTab .nav-pills > li"),
                    active = tabs.filter(".active"),
                    next = active.next("li"),
                    toClick = next.length ? next.find("a") : tabs.eq(0).find("a");
            
                toClick.trigger("click");
            }, 4000);
        </script>
	</head>
	<body>
		<!-- <h1><?= $feed['description'];?></h1> -->
    	<div class="container">
    		<?php if ($feed) {?>
                <div id="bruntalTab" class="row" role="tabpanel">
                    <?php $active = true;?>
                    <?php $i = 1;?>
                    <div class="col-xs-11 col-tab">
                        <div class="tab-content">
                            <?php foreach ($feed['content'] as $entry) {?>
                                <div role="tabpanel" class="tab-pane fade<?= ($active)?' in active':'';?>" id="tab<?= $i;?>">
                                    <div>
                                        <img class="img-responsive" src="<?= $entry['image'];?>" alt="<?= $entry['title'];?>" />
                                    </div>
                                    <div class="title-section">
                                        <a href="<?= $entry['link'];?>" title="<?= $entry['title'];?>" target="_blank">
                                            <?= $entry['title'];?>
                                        </a>
                                    </div>
                                    <div class="date"><?= $entry['dateModified'];?></div>
                                </div>
                                <?php $active = false;?>
                                <?php $i++;?>
                            <?php } ?>
                        </div>
                    </div>
                    <?php $active = true;?>
                    <?php $i = 1;?>
                    <div class="col-xs-1 col-nav">
                        <ul class="nav nav-pills nav-stacked" role="tablist">
                            <?php foreach ($feed['content'] as $entry) {?>
                                <li role="presentation" class="<?= ($active)?'active':'';?>">
                                    <a href="#tab<?= $i;?>" aria-controls="tab<?= $i;?>" role="tab" data-toggle="tab">
                                        <?= $i;?>
                                    </a>
                                </li>
                                <?php $active = false;?>
                                <?php $i++;?>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
    		<?php }?>
        </div>
	</body>
</html>
