<?php
/*
 * @project polar
 * @author Rostislav Greipel
 * @link https://rogr.cz
 * @copyright (c) 2011 - 2021 ROGR All Rights Reserved
 * @license https://rogr.cz/license/eula EULA License
 */
/** @var \App\Application\View\ViewHelper $view */
?>
<div class="row">
    <div class="col-lg-3">

    </div>
    <div class="col-lg-9">
        <section class="card card-primary">
            <header class="card-header">
                <div class="card-actions">
                    <span id="msgNotSaved" class="badge badge-danger d-none">
                        Neuloženo
                    </span>
                </div>
                <h2 class="card-title">
                    Upravit nastavení
                </h2>
            </header>
            <form action="<?= $view->path('admin_program_setting') ?>" method="post" id="frmSetting" class="form-horizontal">
                <div class="card-body">
                    <div class="form-group row">
                        <label class="col-sm-3 control-label text-sm-right pt-2 required" for="show_img_width">Pořad - Šířka obrázku</label>
                        <div class="col-sm-9">
                            <div class="input-group">
                                <input type="text" name="show_img_width" id="show_img_width" class="form-control" value="<?= htmlspecialchars((string) ($setting['show_img_width'] ?? '')) ?>" placeholder="required" required maxlength="100">
                                <span class="input-group-append">
                                    <span class="input-group-text">
                                        [px]
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 control-label text-sm-right pt-2 required" for="show_img_height">Pořad - Výška obrázku</label>
                        <div class="col-sm-9">
                            <div class="input-group">
                                <input type="text" name="show_img_height" id="show_img_height" class="form-control" value="<?= htmlspecialchars((string) ($setting['show_img_height'] ?? '')) ?>" placeholder="required" required maxlength="100">
                                <span class="input-group-append">
                                    <span class="input-group-text">
                                        [px]
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <footer class="card-footer text-right">
                    <button type="submit" name="submit" class="btn btn-primary">Uložit</button>
                    <button type="submit" name="cancel" class="btn btn-default" formnovalidate>Storno</button>
                </footer>
            </form>
        </section>
    </div>
</div>
