<?php
/*
 * @project polar
 * @author Rostislav Greipel
 * @link https://rogr.cz
 * @copyright (c) 2011 - 2021 ROGR All Rights Reserved
 * @license https://rogr.cz/license/eula EULA License
 */
?>

<div class="row">
    <div class="col-lg-6">
        <div class="row">
            <?= $view->include('admin/dashboard/widget-program', [
                'countProgram' => $countProgram,
                'countProgramPremiere' => $countProgramPremiere,
                'countVideo' => $countVideo,
                'countShow' => $countShow,
                'countShowActive' => $countShowActive,
            ]) ?>
            <?= $view->include('admin/dashboard/widget-camera', [
                'countCamera' => $countCamera,
            ]) ?>
            <?= $view->include('admin/dashboard/widget-election', [
                'countElection' => $countElection,
            ]) ?>
            <?= $view->include('admin/dashboard/widget-job', [
                'countJob' => $countJob,
                'countJobOurs' => $countJobOurs,
            ]) ?>
            <?= $view->include('admin/dashboard/widget-page', [
                'countPage' => $countPage,
                'countPageActive' => $countPageActive,
            ]) ?>
            <?= $view->include('admin/dashboard/widget-user', [
                'countUsers' => $countUsers,
                'countUsersActive' => $countUsersActive,
            ]) ?>
        </div>
    </div>
    <div class="col-lg-6">
        <?= $view->include('admin/dashboard/log') ?>
    </div>
</div>
