<?php
/*
 * @project polar
 * @author Rostislav Greipel
 * @link https://rogr.cz
 * @copyright (c) 2011 - 2021 ROGR All Rights Reserved
 * @license https://rogr.cz/license/eula EULA License
 */

?>

<h4 class="d-lg-none">
    Program
</h4>
<div class="timeline timeline-simple changelog">
    <div class="scrollable visible-slider colored-slider" data-plugin-scrollable style="height: 425px;">
        <div class="scrollable-content">
            <div class="tm-body">
                <ol class="tm-items">
                    <?php $datetime = new DateTime('2021-01-01') ?>
                    <div class="tm-title">
                        <h5 class="m-0 pt-2 pb-2 text-uppercase">
                            2021
                        </h5>
                    </div>
                    <?php $datetime = new DateTime('2021-09-08') ?>
                    <li>
                        <div class="tm-box">
                            <h4>
                                0.0.1
                            </h4>
                            –
                            <span class="release-date">
                                <?= $datetime->format('j. n. Y') ?>
                            </span>
                            <ul class="list-unstyled">
                                <li>
                                    <span class="badge badge-primary">
                                        První vydání
                                    </span>
                                    -
                                    První vydání
                                </li>
                            </ul>
                        </div>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
