<?php
/*
 * @project ferritenergy
 * @author Rostislav Greipel
 * @link https://rogr.cz
 * @copyright (c) 2011 - 2021 ROGR All Rights Reserved
 * @license https://rogr.cz/license/eula EULA License
 */
?>

<section class="card card-featured-top card-featured-primary mb-4">
    <div class="card-body">
        <div class="widget-summary">
            <div class="widget-summary-col widget-summary-col-icon">
                <div class="summary-icon bg-primary hvr-grow">
                    <i class="fa fa-newspaper"></i>
                </div>
            </div>
            <div class="widget-summary-col">
                <div class="summary">
                    <h4 class="title text-nowrap">
                        Banner
                    </h4>
                    <div class="info text-nowrap">
                        <strong class="amount">
                            <?= $countBanner ?? 0 ?>
                        </strong>
                        <span class="text-primary">
                            (<?= $countBannerFuture ?? 0 ?> budoucích)
                        </span>
                    </div>
                </div>
                <div class="summary-footer">
                    <span class="pull-left" data-toggle="tooltip" data-placement="right" title="Verze">
                        0.0.6
                    </span>
                    <a href="<?= $view->path('admin_banner_leaderboard_list') ?>" class="text-muted text-uppercase">
                        <i class="fa fa-fw fa-ellipsis-v"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
