<?php
/*
 * @project polar
 * @author Rostislav Greipel
 * @link https://rogr.cz
 * @copyright (c) 2011 - 2021 ROGR All Rights Reserved
 * @license https://rogr.cz/license/eula EULA License
 */

$scheme = $scheme ?? 'dark';
$schemeOpposite = $scheme === 'dark' ? 'light' : 'dark';

$srcImage = $view->asset('data/page/!default-page.png') . '?ver=' . date('YmdHis');
$imageValue = $post['image'] ?? null;
if ($imageValue) {
    $srcImage = $view->asset($imageValue);
}

$view->addHeadLink('stylesheet', '/vendor/admin/file-upload/css/file-upload.css');
$view->addBodyScript('/vendor/admin/file-upload/js/ui-widget.js');
$view->addBodyScript('/vendor/admin/file-upload/js/iframe-transport.js');
$view->addBodyScript('/vendor/admin/file-upload/js/file-upload.js');

// Změna schématu
$view->addInlineScript(
    '$("#btnThemeChange").on("click", function (event) {
        event.preventDefault();
        let scheme = "dark";
        let html = $("html");

        if (html.hasClass("dark")) {
            scheme = "light";
        }
        
        let image = $(".image-inner-container img");
        let btnImage = $(".image-button");
        
        if (scheme === "dark") {
            image.removeClass("border-color-light").addClass("border-color-dark");
            btnImage.removeClass("bg-dark").addClass("bg-light");
            btnImage.find("i").removeClass("text-color-light").addClass("text-color-dark");
        } else {
            image.removeClass("border-color-dark").addClass("border-color-light");
            btnImage.removeClass("bg-light").addClass("bg-dark");
            btnImage.find("i").removeClass("text-color-dark").addClass("text-color-light");
        }
    });'
);

// Nahrání obrázku
$view->addInlineScript(
    '$("#fileupload").fileupload({
        formData: {
            page_id: ' . $page['id'] . '
        },
        dropZone: "#image",
        dataType: "json",
        add: function (e, data) {
            $("#image .progress").removeClass("d-none");
            $("#image .progress .progress-bar").css("width", "0%");
            data.submit();
        },
        progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $("#image .progress .progress-bar").css("width", progress + "%");
        },
        done: function (e, data) {
            $("#image .progress .progress-bar").removeClass("progress-bar-striped progress-bar-animated active");
            $("#image .progress").addClass("d-none");
            $("#image .image-outer-container img").attr("src", "/" + data.result.url);
            $("input[name=image]").val(data.result.url);
            if (data.result.error) {
                new PNotify({
                    title: "Obrázek stránky",
                    text: data.result.error,
                    type: "error"
                });
            } else {
                new PNotify({
                    title: "Obrázek stránky",
                    text: "Obrázek stránky byl úspěšně nahrán",
                    type: "success"
                });
            }
        },
        fail: function (e, data) {
            $("#image .progress .progress-bar").removeClass("progress-bar-striped progress-bar-animated active");
            $("#image .progress").addClass("d-none");
            new PNotify({
                title: "Obrázek stránky",
                text: "Obrázek stránky nebyl úspěšně nahrán",
                type: "error"
            });
        }
    });'
);

// Nahrání obrázku (klik na ikonu)
$view->addInlineScript(
    '$("#image .image-outer-container .image-inner-container .image-button").click(function(e){
        $("#fileupload").click();
    });'
);

// Smazání obrázku (klik na ikonu)
$view->addInlineScript(
    '$("#image .image-outer-container .image-inner-container .delete-button").click(function(e){
        $.post("' . $view->path('admin_page_set_default_image') . '",
            {
                page_id: ' . $page['id'] . ',
                field: "image"
            },
            function(json) {
                if (json.success) {
                    var notice = new PNotify({
                        title: "Úspěch",
                        text: "Obrázek stránky byl nastaven na výchozí",
                        type: "success",
                        addclass: "click-2-close",
                        buttons: {
                            sticker: false
                        }
                    });
                    $("input[name=image]").val(json.url);
                    $("#image .image-outer-container img").attr("src", "/" + json.url);
                } else {
                    var notice = new PNotify({
                        title: "Chyba",
                        text: "Nelze nastavit obrázek stránky na výchozí",
                        type: "error",
                        addclass: "click-2-close",
                        buttons: {
                            sticker: false
                        }
                    });
                }
            }, 
            "json"      
        );
    });'
);
?>

<div class="row">
    <div class="col-lg-3">
        <div id="image">
            <h3 class="mt-0">
                Obrázek
                <small class="pull-right text-muted">
                    (<?= $setting['img_width'] ?>px x <?= $setting['img_height'] ?>px)
                </small>
            </h3>
            <div class="mb-4">
                <div class="image-outer-container d-inline-flex">
                    <div class="image-inner-container bg-primary">
                        <img class="img-fluid border-color-<?= $scheme ?>" src="<?= $srcImage ?>" alt="">
                        <span class="delete-button bg-danger">
                            <i class="fa fa-trash-alt text-color-light"></i>
                        </span>
                        <span class="image-button bg-<?= $schemeOpposite ?>">
                            <i class="fa fa-camera text-color-<?= $scheme ?>"></i>
                        </span>
                    </div>
                    <input id="fileupload" class="image-input" type="file" name="file" data-url="<?= $view->path('admin_page_upload_image') ?>" accept="image/*">
                </div>
            </div>
            <div class="progress mb-3 d-none">
                <div class="progress-bar progress-bar-primary" role="progressbar" style="width: 0">
                    <span class="sr-only">0%</span>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-9">
        <section class="card card-primary">
            <header class="card-header">
                <div class="card-actions">
                    <span id="msgNotSaved" class="badge badge-danger d-none">
                        Neuloženo
                    </span>
                </div>
                <h2 class="card-title">
                    Upravit stránku
                </h2>
            </header>
            <?= $view->include('page/admin/pageForm', [
                'view' => $view,
                'post' => $post,
                'errors' => $errors,
                'lang' => $lang,
                'page_id' => $page['id'],
                'submitLabel' => 'Uložit',
                'submitClass' => 'btn-primary',
            ]) ?>
        </section>
    </div>
</div>
