<?php
/*
 * @project polar
 * @author Rostislav Greipel
 * @link https://rogr.cz
 * @copyright (c) 2011 - 2021 ROGR All Rights Reserved
 * @license https://rogr.cz/license/eula EULA License
 */
/** @var \App\Application\View\ViewHelper $view */

$view->addBodyScript($view->asset('vendor/admin/bootstrap-maxlength/js/bootstrap-maxlength.min.js'));

if ($success) {
	$view->addInlineScript(
		'var notice = new PNotify({
			title: "Stránky",
			text: "' . addslashes($success) . '",
			type: "success",
			addclass: "click-2-close",
			buttons: {
				sticker: false
			}
		});'
	);
}
if ($error) {
	$view->addInlineScript(
		'var notice = new PNotify({
			title: "Chyba",
			text: "' . addslashes($error) . '",
			type: "error",
			addclass: "click-2-close",
			buttons: {
				sticker: false
			}
		});'
	);
}
?>

<div class="row">
    <div class="col-lg-3">

    </div>
    <div class="col-lg-9">
        <section class="card card-primary">
            <header class="card-header">
                <div class="card-actions">
                    <span id="msgNotSaved" class="badge badge-danger d-none">
                        Neuloženo
                    </span>
                </div>
                <h2 class="card-title">
                    Upravit nastavení
                </h2>
            </header>

            <form action="<?= $view->path('admin_page_setting') ?>" method="post" class="form-horizontal" id="frmSetting">

                <div class="card-body">
                    <div class="form-group row">
                        <label class="col-sm-3 control-label text-sm-right pt-2 required">Šířka obrázku</label>
                        <div class="col-sm-9">
                            <div class="input-group">
                                <input type="text" name="img_width" class="form-control" placeholder="povinné" required maxlength="100" data-plugin-maxlength data-rule-rangeLength="[0, 100]" value="<?= htmlspecialchars($setting['img_width'] ?? '800') ?>">
                                <span class="input-group-append">
                                    <span class="input-group-text">
                                        [px]
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 control-label text-sm-right pt-2 required">Výška obrázku</label>
                        <div class="col-sm-9">
                            <div class="input-group">
                                <input type="text" name="img_height" class="form-control" placeholder="povinné" required maxlength="100" data-plugin-maxlength data-rule-rangeLength="[0, 100]" value="<?= htmlspecialchars($setting['img_height'] ?? '450') ?>">
                                <span class="input-group-append">
                                    <span class="input-group-text">
                                        [px]
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 control-label text-sm-right pt-2 required">Patička číslo 1</label>
                        <div class="col-sm-9">
                            <div class="input-group">
                                <input type="text" name="footer_number_1" class="form-control" placeholder="povinné" required maxlength="100" data-plugin-maxlength data-rule-rangeLength="[0, 100]" value="<?= htmlspecialchars($setting['footer_number_1'] ?? '') ?>">
                                <span class="input-group-append">
                                    <span class="input-group-text">
                                        [diváků]
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 control-label text-sm-right pt-2 required">Patička číslo 2</label>
                        <div class="col-sm-9">
                            <div class="input-group">
                                <input type="text" name="footer_number_2" class="form-control" placeholder="povinné" required maxlength="100" data-plugin-maxlength data-rule-rangeLength="[0, 100]" value="<?= htmlspecialchars($setting['footer_number_2'] ?? '') ?>">
                                <span class="input-group-append">
                                    <span class="input-group-text">
                                        [diváků]
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 control-label text-sm-right pt-2 required">Patička číslo 3</label>
                        <div class="col-sm-9">
                            <div class="input-group">
                                <input type="text" name="footer_number_3" class="form-control" placeholder="povinné" required maxlength="100" data-plugin-maxlength data-rule-rangeLength="[0, 100]" value="<?= htmlspecialchars($setting['footer_number_3'] ?? '') ?>">
                                <span class="input-group-append">
                                    <span class="input-group-text">
                                        [diváků]
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 control-label text-sm-right pt-2 required">Patička číslo 4</label>
                        <div class="col-sm-9">
                            <div class="input-group">
                                <input type="text" name="footer_number_4" class="form-control" placeholder="povinné" required maxlength="100" data-plugin-maxlength data-rule-rangeLength="[0, 100]" value="<?= htmlspecialchars($setting['footer_number_4'] ?? '') ?>">
                                <span class="input-group-append">
                                    <span class="input-group-text">
                                        [diváků]
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <footer class="card-footer text-right">
                    <button type="submit" name="submit" class="btn btn-primary">Uložit</button>
                    <button type="submit" name="cancel" class="btn btn-default" formnovalidate>Zrušit</button>
                </footer>
            </form>

        </section>
    </div>
</div>
