# config/routes.yaml
news:
  resource: routes/news.yaml

job:
  resource: routes/job.yaml

camera:
  resource: routes/camera.yaml

banner:
  resource: routes/banner.yaml

app_home:
  path: /
  controller: App\Application\Controller\Web\ApplicationController::index

app_search:
  path: /hledat
  controller: App\Application\Controller\Web\ApplicationController::search
  methods: [GET]

app_send_email:
  path: /json-write/send-email
  controller: App\Application\Controller\Web\ApplicationWriteController::sendEmail
  methods: [POST]
