# config/routes.yaml
news:
  resource: routes/news.yaml

job:
  resource: routes/job.yaml

camera:
  resource: routes/camera.yaml

banner:
  resource: routes/banner.yaml

page:
  resource: routes/page.yaml

page_generated:
  resource: routes/page_generated.yaml

admin:
  resource: routes/admin.yaml

app_home:
  path: /
  controller: App\Application\Controller\Web\ApplicationController::index

app_search:
  path: /hledani
  controller: App\Application\Controller\Web\ApplicationController::search
  methods: [GET]

app_send_email:
  path: /json-write/send-email
  controller: App\Application\Controller\Web\ApplicationWriteController::sendEmail
  methods: [POST]

app_hd:
  path: /hd
  controller: App\Application\Controller\Web\ApplicationController::hd

app_polar2:
  path: /polar2
  controller: App\Application\Controller\Web\ApplicationController::polar2

app_privacy_policy:
  path: /ochrana-osobnich-udaju
  controller: App\Application\Controller\Web\ApplicationController::privacyPolicy

app_access_denied:
  path: /pristup-odepren
  controller: App\Application\Controller\Web\ApplicationController::accessDenied

app_rss:
  path: /rss
  controller: App\Application\Controller\Web\ApplicationController::rss

app_sitemap:
  path: /mapa-stranek
  controller: App\Application\Controller\Web\ApplicationController::sitemap

app_sitemap_xml:
  path: /sitemap.xml
  controller: App\Application\Controller\Web\ApplicationController::sitemapXml

app_sitemap_default_xml:
  path: /sitemap-default.xml
  controller: App\Application\Controller\Web\ApplicationController::sitemapDefaultXml

app_robots_txt:
  path: /robots.txt
  controller: App\Application\Controller\Web\ApplicationController::robotsTxt

app_embed_playerjs:
  path: /embed-playerjs
  controller: App\Application\Controller\Web\ApplicationController::embedPlayerjs

# Authorization
app_login:
  path: /prihlaseni
  controller: App\Authorization\Controller\SecurityController::login

app_logout:
  path: /odhlaseni
  controller: App\Authorization\Controller\SecurityController::logout

app_sign_out:
  path: /autorizace/odhlasit
  controller: App\Authorization\Controller\SecurityController::signOut
