# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.PUBLIC_PATH: '%kernel.project_dir%/public'
    app.HOURS_DELETE_LABELS: 24
    app.LIGHT_URL: 'https://light.polar.cz/videa/polar/'
    app.LIGHT_PATH_WITHOUT_HTTPS: '/data_webytv/dp/polar/'
    app.LIGHT_URL_WITHOUT_HTTPS: 'http://plainvod.polar.cz/videa/polar/'
    app.LIGHT_PATH: '%env(LIGHT_PATH)%'
    app.GOOGLE_ANALYTICS_ID: '%env(GOOGLE_ANALYTICS_ID)%'
    app.GOOGLE_MAP_KEY: '%env(GOOGLE_MAP_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # database
    App\News\Repository\PlaykitRepository:
        arguments:
            $connection: '@doctrine.dbal.playkit_connection'
            $HOURS_DELETE_LABELS: '%app.HOURS_DELETE_LABELS%'

    App\News\Repository\NewsRepository:
        arguments:
            $HOURS_DELETE_LABELS: '%app.HOURS_DELETE_LABELS%'

    App\Job\Repository\JobRepository:
        arguments:
            $connection: '@doctrine.dbal.playkit_connection'

    App\Job\Repository\JobOurRepository:
        arguments:
            $connection: '@doctrine.dbal.playkit_connection'

    App\News\Repository\CrawlRepository:
        arguments:
            $connection: '@doctrine.dbal.playkit_connection'

    App\News\Repository\TickerRepository:
        arguments:
            $connection: '@doctrine.dbal.playkit_connection'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\News\Controller\:
        resource: '../src/News/Controller/'
        tags: ['controller.service_arguments']
        bind:
            $PUBLIC_PATH: '%app.PUBLIC_PATH%'
            $LIGHT_URL: '%app.LIGHT_URL%'

    App\Application\Controller\:
        resource: '../src/Application/Controller/'
        tags: ['controller.service_arguments']

    App\Camera\Controller\:
        resource: '../src/Camera/Controller/'
        tags: ['controller.service_arguments']

    App\Job\Controller\:
        resource: '../src/Job/Controller/'
        tags: ['controller.service_arguments']

    App\Banner\Controller\:
        resource: '../src/Banner/Controller/'
        tags: ['controller.service_arguments']
        bind:
            $PUBLIC_PATH: '%app.PUBLIC_PATH%'

    App\Admin\Controller\:
        resource: '../src/Admin/Controller/'
        tags: ['controller.service_arguments']

    App\User\Controller\:
        resource: '../src/User/Controller/'
        tags: ['controller.service_arguments']
        bind:
            $PUBLIC_PATH: '%app.PUBLIC_PATH%'

    App\Authorization\Controller\:
        resource: '../src/Authorization/Controller/'
        tags: ['controller.service_arguments']

    App\Page\Controller\:
        resource: '../src/Page/Controller/'
        tags: ['controller.service_arguments']
        bind:
            $PUBLIC_PATH: '%app.PUBLIC_PATH%'

    App\Program\Controller\Web\:
        resource: '../src/Program/Controller/Web/'
        tags: ['controller.service_arguments']

    App\Program\Controller\Web\ShowController:
        tags: ['controller.service_arguments']
        bind:
            $LIGHT_URL: '%app.LIGHT_URL%'
            $PUBLIC_PATH: '%app.PUBLIC_PATH%'

    App\Program\Controller\Web\ShowexController:
        tags: ['controller.service_arguments']
        bind:
            $LIGHT_URL: '%app.LIGHT_URL%'

    App\Program\Controller\Admin\:
        resource: '../src/Program/Controller/Admin/'
        tags: ['controller.service_arguments']

    App\Program\Controller\Admin\SettingController:
        tags: ['controller.service_arguments']
        bind:
            $PUBLIC_PATH: '%app.PUBLIC_PATH%'

    App\Program\Controller\Admin\ShowListController:
        tags: ['controller.service_arguments']
        bind:
            $PUBLIC_PATH: '%app.PUBLIC_PATH%'

    App\Program\Controller\Admin\ShowWriteController:
        tags: ['controller.service_arguments']
        bind:
            $PUBLIC_PATH: '%app.PUBLIC_PATH%'

    App\Program\Controller\Admin\ShowexListController:
        tags: ['controller.service_arguments']
        bind:
            $PUBLIC_PATH: '%app.PUBLIC_PATH%'

    App\Program\Controller\Admin\ShowexWriteController:
        tags: ['controller.service_arguments']
        bind:
            $PUBLIC_PATH: '%app.PUBLIC_PATH%'

    App\Program\Controller\Admin\VideoWriteController:
        tags: ['controller.service_arguments']
        bind:
            $PUBLIC_PATH: '%app.PUBLIC_PATH%'
            $LIGHT_PATH: '%app.LIGHT_PATH%'
            $LIGHT_URL: '%app.LIGHT_URL%'

    App\Program\Controller\Admin\ProgramWriteController:
        tags: ['controller.service_arguments']
        bind:
            $PUBLIC_PATH: '%app.PUBLIC_PATH%'
            $LIGHT_URL: '%app.LIGHT_URL%'

    App\Program\Controller\Admin\VideoexWriteController:
        tags: ['controller.service_arguments']
        bind:
            $PUBLIC_PATH: '%app.PUBLIC_PATH%'
            $LIGHT_PATH: '%app.LIGHT_PATH%'
            $LIGHT_URL: '%app.LIGHT_URL%'

    App\Application\View\PhtmlRenderer:
        arguments:
            $templatesDir: '%kernel.project_dir%/templates'
            $basePath: ''
            $globals:
                HOURS_DELETE_LABELS: '%app.HOURS_DELETE_LABELS%'
                GOOGLE_MAP_KEY: '%app.GOOGLE_MAP_KEY%'

    App\Application\EventSubscriber\LayoutSubscriber:
        arguments:
            $GOOGLE_ANALYTICS_ID: '%app.GOOGLE_ANALYTICS_ID%'

    App\Application\EventSubscriber\ErrorSubscriber:
        arguments:
            $environment: '%kernel.environment%'

    App\Application\EventSubscriber\FatalErrorHandler:
        arguments:
            $templatesDir: '%kernel.project_dir%/templates'

    App\Banner\EventListener\BannerGlobalListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


