<h4 class="d-lg-none">
    Banner
</h4>
<div class="timeline timeline-simple changelog">
    <div class="scrollable visible-slider colored-slider" data-plugin-scrollable style="height: 425px;">
        <div class="scrollable-content">
            <div class="tm-body">
                <ol class="tm-items">
                    <?php $datetime = new DateTime('2021-01-01') ?>
                    <div class="tm-title">
                        <h5 class="m-0 pt-2 pb-2 text-uppercase">
                            <?= $view->dateFormat($datetime, IntlDateFormatter::FULL, IntlDateFormatter::NONE, $locale, 'yyyy') ?>
                        </h5>
                    </div>
                    <?php $datetime = new DateTime('2021-08-17') ?>
                    <li>
                        <div class="tm-box">
                            <h4>
                                0.0.6
                            </h4>
                            –
                            <span class="release-date">
                                <?= $view->dateFormat($datetime, IntlDateFormatter::LONG, IntlDateFormatter::NONE) ?>
                            </span>
                            <ul class="list-unstyled">
                                <li>
                                    <span class="badge badge-info">
                                        Aktualizováno
                                    </span>
                                    -
                                    PHP 8
                                </li>
                            </ul>
                        </div>
                    </li>
                    <?php $datetime = new DateTime('2021-02-03') ?>
                    <li>
                        <div class="tm-box">
                            <h4>
                                0.0.5
                            </h4>
                            –
                            <span class="release-date">
                                <?= $view->dateFormat($datetime, IntlDateFormatter::LONG, IntlDateFormatter::NONE) ?>
                            </span>
                            <ul class="list-unstyled">
                                <li>
                                    <span class="badge badge-danger">
                                        Opraveno
                                    </span>
                                    -
                                    Nahrávání obrázků - Dropbox
                                </li>
                            </ul>
                        </div>
                    </li>
                    <?php $datetime = new DateTime('2021-01-20') ?>
                    <li>
                        <div class="tm-box">
                            <h4>
                                0.0.4
                            </h4>
                            –
                            <span class="release-date">
                                <?= $view->dateFormat($datetime, IntlDateFormatter::LONG, IntlDateFormatter::NONE) ?>
                            </span>
                            <ul class="list-unstyled">
                                <li>
                                    <span class="badge badge-primary">
                                        Přidáno
                                    </span>
                                    -
                                    Zobrazení - 3 sloupce
                                </li>
                                <li>
                                    <span class="badge badge-primary">
                                        Přidáno
                                    </span>
                                    -
                                    Zobrazení - Poslední banner
                                </li>
                            </ul>
                        </div>
                    </li>
                    <?php $datetime = new DateTime('2021-01-10') ?>
                    <li>
                        <div class="tm-box">
                            <h4>
                                0.0.3
                            </h4>
                            –
                            <span class="release-date">
                                <?= $view->dateFormat($datetime, IntlDateFormatter::LONG, IntlDateFormatter::NONE) ?>
                            </span>
                            <ul class="list-unstyled">
                                <li>
                                    <span class="badge badge-primary">
                                        Přidáno
                                    </span>
                                    -
                                    Nastavení - Velikost obrázku
                                </li>
                            </ul>
                        </div>
                    </li>
                    <?php $datetime = new DateTime('2021-01-04') ?>
                    <li>
                        <div class="tm-box">
                            <h4>
                                0.0.2
                            </h4>
                            –
                            <span class="release-date">
                                <?= $view->dateFormat($datetime, IntlDateFormatter::LONG, IntlDateFormatter::NONE) ?>
                            </span>
                            <ul class="list-unstyled">
                                <li>
                                    <span class="badge badge-info">
                                        Aktualizováno
                                    </span>
                                    -
                                    Revize kódu
                                </li>
                            </ul>
                        </div>
                    </li>
                </ol>
                <ol class="tm-items">
                    <?php $datetime = new DateTime('2020-01-01') ?>
                    <div class="tm-title">
                        <h5 class="m-0 pt-2 pb-2 text-uppercase">
                            <?= $view->dateFormat($datetime, IntlDateFormatter::FULL, IntlDateFormatter::NONE, $locale, 'yyyy') ?>
                        </h5>
                    </div>
                    <?php $datetime = new DateTime('2020-05-12') ?>
                    <li>
                        <div class="tm-box">
                            <h4>
                                0.0.1
                            </h4>
                            –
                            <span class="release-date">
                                <?= $view->dateFormat($datetime, IntlDateFormatter::LONG, IntlDateFormatter::NONE) ?>
                            </span>
                            <ul class="list-unstyled">
                                <li>
                                    <span class="badge badge-primary">
                                        První vydání
                                    </span>
                                    -
                                    První vydání
                                </li>
                            </ul>
                        </div>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
