<?php
/*
 * @project polar
 * @author Rostislav Greipel
 * @link https://rogr.cz
 * @copyright (c) 2011 - 2021 ROGR All Rights Reserved
 * @license https://rogr.cz/license/eula EULA License
 */
?>

<div class="row">
    <div class="col-xl-6">
        <section class="card">
            <header class="card-header">
                <h2 class="card-title">Uživatelé</h2>
            </header>
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <strong><?= $countUsers ?></strong> celkem
                    </div>
                    <div class="col">
                        <strong><?= $countUsersActive ?></strong> aktivních
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
