<?php
/** @var \App\Application\View\ViewHelper $view */

$view->addHeadLink('stylesheet', $view->asset('vendor/admin/bootstrap-table/css/bootstrap-table.min.css'));

$view->addBodyScript($view->asset('vendor/admin/bootstrap-table/js/bootstrap-table.min.js'));
$view->addBodyScript($view->asset('vendor/admin/bootstrap-table/js/locale/' . $locale . '.min.js'));
$view->addBodyScript($view->asset('vendor/admin/bootstrap-table/extension/cookie/js/cookie.min.js'));
$view->addBodyScript($view->asset('vendor/admin/bootstrap-table/extension/mobile/js/mobile.min.js'));
$view->addBodyScript($view->asset('vendor/admin/moment/js/moment.min.js'));
$view->addBodyScript($view->asset('vendor/admin/moment/js/locale/' . $locale . '.min.js'));

// Zobrazení náhledu
$view->addInlineScript(
    '$("#btblVideo").on("post-body.bs.table", function (e, data) {
        $(".image-popup-no-margins").magnificPopup({
            type: "image",
            image: {
                verticalFit: true
            },
            zoom: {
                enabled: true,
                duration: 300
            }
        });
    });'
);

// Smazání videa
$view->addInlineScript(
    '$("#btblVideo").on("post-body.bs.table", function (e, data) {
        $(".btblBtnDeleteVideo").unbind("click").bind("click", function() {
            var id = $(this).data("video-id");
            $.post("' . $view->path('admin_program_videoex_json_get_video') . '",
                {
                    id: id
                },
                function(json) {
                    if (json.success) {
                        $("#modalDanger .card-title").html("Odstranit mimořádné video");
                        $("#modalDanger .modal-text h4").html("Opravdu chcete smazat video?<br><strong>\"" + json.video.name + "\"</strong>" );
                        $("#modalDanger .modal-text p").html("Všechny závislosti budou odstraněny. Tuto akci nelze vrátit zpět!");
                        var btnConfirm = $("#modalDanger .card-footer button.modal-confirm");
                        
                        $.magnificPopup.open({
                            items: {src: "#modalDanger"},
                            type: "inline",
                            fixedContentPos: false,
                            fixedBgPos: true,
                            overflowY: "auto",
                            closeBtnInside: true,
                            preloader: false,
                            midClick: true,
                            removalDelay: 300,
                            mainClass: "my-mfp-slide-bottom",
                            modal: true,
                            callbacks: {
                                open: function() {
                                    btnConfirm.unbind("click").click(function(e){
                                        e.preventDefault();
                                        $.post("' . $view->path('admin_program_videoex_json_delete_video') . '",
                                            {
                                                id: id
                                            },
                                            function(json) {
                                                if (json.success) {
                                                    var notice = new PNotify({
                                                        title: "Uloženo",
                                                        text: "Video bylo odstraněno!",
                                                        type: "success",
                                                        addclass: "click-2-close",
                                                        buttons: {
                                                            sticker: false
                                                        }
                                                    });
                                                    $("#btblVideo").bootstrapTable("refresh", {"silent": true});
                                                }else{
                                                    var notice = new PNotify({
                                                        title: "Chyba",
                                                        text: "Nelze odstranit video!",
                                                        type: "error",
                                                        addclass: "click-2-close",
                                                        buttons: {
                                                            sticker: false
                                                        }
                                                    });
                                                }
                                                $.magnificPopup.close();
                                            }, 
                                            "json"      
                                        );
                                    });
                                }
                            }
                        });
                    } else {
                        var notice = new PNotify({
                            title: "Chyba",
                            text: "Nelze načíst informace o videu!",
                            type: "error",
                            addclass: "click-2-close",
                            buttons: {
                                sticker: false
                            }
                        });
                        $.magnificPopup.close();
                        $("#btblVideo").bootstrapTable("refresh", {"silent": true});
                    }
                }, 
                "json"      
            );
        });
    });'
);

// Načtení videí
$view->addInlineScript(
    'var btn = $("#btnLoadVideos");
    var modal = $("#modalProgress");
    btn.click(function(e){
        e.preventDefault();
        btn.button("loading");
        modal.find(".card-title").html("Načítání mimořádných videí");
        $.magnificPopup.open({
            items: {src: "#modalProgress"},
            closeOnBgClick: false,
            callbacks: {
                close: function() {
                    btn.button("reset");
                },
            }
        });
        startProgress();
    });
    
    function startProgress(){
        modal.find(".progress-bar").css("width", "0%");
        modal.find(".percent").html("");
        modal.find(".timeTaken").html("0s celkem");
        modal.find(".timeRemaining").html("0s zbývá");
        modal.find(".modal-text .scrollable-content").html("Čekejte prosím...");
        modal.find(".btn-close").hide();
        modal.find("button.modal-dismiss").attr("disabled", true);
        var iFrame = document.createElement("iframe");
        iFrame.className = "loadData";
        document.getElementsByTagName("body")[0].appendChild(iFrame);
        iFrame.src = "' . $view->path('admin_program_videoex_json_load_videos') . '?cron=false";
    }
    function updateProgress(data){
        modal.find(".progress-bar").css("width", Math.round(data.percent) + "%");
        modal.find(".percent").html(Math.round(data.percent));
        modal.find(".timeTaken").html(data.timeTaken + "s celkem");
        if (data.timeRemaining) modal.find(".timeRemaining").html(((data.timeRemaining)?data.timeRemaining:0) + "s zbývá");
        if (data.text) modal.find(".modal-text .scrollable-content").prepend(data.text + "<br />");
    }
    function finishProgress(){
        modal.find(".progress-bar").css("width", "100%");
        modal.find(".percent").html("100");
        modal.find(".btn-close").show();
        modal.find("button.modal-dismiss").removeAttr("disabled");
        modal.find(".timeRemaining").html("");
        $(".modal-text .nano").nanoScroller();
        $("[data-toggle=\"tooltip\"]").tooltip();
        $("#btblVideo").bootstrapTable("refresh", {"silent": true});
    }'
);
?>

<div class="tabs">
    <ul class="nav nav-tabs nav-justified">
        <li class="nav-item">
            <a class="nav-link" href="<?= $view->path('admin_program_video_list') ?>">
                Videa
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="#shows" data-toggle="tab">
                Mimořádná videa
            </a>
        </li>
    </ul>
    <div class="tab-content">
        <div id="shows" class="tab-pane active">
            <div id="toolbar">
                <div class="btn-group">
                    <button id="btnLoadVideos" class="btn btn-primary">
                        <i class="fa fa-fw fa-download"></i>
                        <span class="hidden-sm hidden-xs">
                            Načíst nová videa
                        </span>
                    </button>
                    <a href="<?= $view->path('admin_program_videoex_json_load_videos') ?>?cron=true" class="btn btn-default" title="CRON"
                       target="_blank">
                        CRON
                    </a>
                </div>
                <span class="badge bg-info rounded-pill text-2 text-dark ml-3">
                    Poslední načtení:
                    <?php
                        try {
                            $date = new DateTime($setting['videoex_update_date']);
                            $fmt = new IntlDateFormatter($locale, IntlDateFormatter::LONG, IntlDateFormatter::SHORT, null, null, 'd. MMMM Y, HH:mm');
                            echo $fmt->format($date);
                        } catch (Exception $e) {
                            echo 'NaN';
                        }
                    ?>
                </span>
            </div>
            <table id="btblVideo"
                   data-url="<?= $view->path('admin_program_videoex_json_get_list') ?>"
                   data-toggle="table"
                   data-show-search-button="true"
                   data-show-search-clear-button="true"
                   data-valign="middle"
                   data-sort-name="id"
                   data-sort-order="desc"
                   data-toolbar="#toolbar"
                   data-cookie-id-table="USER-<?= $identity->getUserIdentifier() ?>-videoexTable"
                   data-mobile-responsive="true"
                   data-page-size="13">
                <thead>
                <tr>
                    <th class="text-nowrap width-nowrap"
                        data-formatter="optionsFormatter"
                        data-align="center">
                        <i class="fa fa-cogs" data-toggle="tooltip" data-placement="right" title="Možnosti"></i>
                        <span class="d-sm-none">
                            Možnosti
                        </span>
                    </th>
                    <th data-field="id"
                        class="text-nowrap width-nowrap"
                        data-sortable="true"
                        data-visible="false">
                        ID
                    </th>
                    <th data-field="name"
                        class="width-nowrap p-0"
                        data-formatter="imageFormatter"
                        data-align="center">
                        <i class="fa fa-video" data-toggle="tooltip" data-placement="right" title="Video"></i>
                        <span class="d-sm-none">
                            Video
                        </span>
                    </th>
                    <th data-field="title"
                        class="text-truncate"
                        data-sortable="true">
                        Titulek
                    </th>
                    <th data-field="show_title"
                        class="text-truncate"
                        data-sortable="true">
                        Pořad
                    </th>
                    <th data-field="path"
                        class="text-nowrap width-nowrap"
                        data-sortable="true">
                        Cesta
                    </th>
                    <th data-field="name"
                        class="text-truncate"
                        data-sortable="true">
                        Název
                    </th>
                    <th data-field="showed"
                        class="text-nowrap width-nowrap"
                        data-formatter="showedFormatter"
                        data-sortable="true">
                        Shlédnuto
                    </th>
                </tr>
                </thead>
            </table>

            <script>
                function optionsFormatter(value, row) {
                    let url = "<?= $view->path('admin_program_videoex_list') ?>/upravit";
                    let data = '';
                    data += '<div class="btn-group pb-sm-0 pb-2">';
                    data += '<a href="' + url + "/" + row.id + '" class="btn btn-sm btn-success"><i class="fa fa-edit"></i> <span class="d-none">Upravit</span></a> ';
                    data += '<button data-video-id="' + row.id + '" class="btblBtnDeleteVideo btn btn-sm btn-danger"><i class="fa fa-trash-alt"></i> <span class="d-none">Odstranit</span></button>';
                    data += '</div>';
                    return data;
                }

                function imageFormatter(value) {
                    if (value) {
                        let randNum = Math.floor(Math.random() * 999) + 1;
                        return '<a class="image-popup-no-margins cur-zoom-in" href="/data/mimoradne/thumbs/' + value + '.jpg?' + randNum + '">' +
                            '<img src="/data/mimoradne/thumbs/' + value + '-260x146.jpg?' + randNum + '" height="48" alt="" />' +
                            '</a>';
                    }
                    return '';
                }

                function showedFormatter(value) {
                    if (value) {
                        return number_format(value, 0, ',', ' ') + " x";
                    } else {
                        return "0 x";
                    }
                }
            </script>
        </div>
    </div>
</div>

<?= $view->include('admin/modal/danger') ?>
<?= $view->include('admin/modal/progress') ?>
