<?php
/** @var \App\Application\View\ViewHelper $view */

/** @var int $page */
/** @var int $total */
/** @var int $limit */
/** @var string $query */
/** @var int|null $region_id */
/** @var int|null $city_id */
/** @var int|null $page_porady */

$pageCount = (int) ceil($total / $limit);

if ($pageCount <= 1) {
    return;
}

$previous     = $page > 1 ? $page - 1 : null;
$next         = $page < $pageCount ? $page + 1 : null;
$pagesInRange = range(max(1, $page - 4), min($pageCount, $page + 4));
$firstItemNumber = ($page - 1) * $limit + 1;
$lastItemNumber  = min($page * $limit, $total);

$urlFor = function(int $p) use ($view, $query, $region_id, $city_id, $page_porady): string {
    return $view->path('app_search') . '?q=' . urlencode($query) . '&r=' . ($region_id ?? '') . '&c=' . ($city_id ?? '') . '&p=' . $p . '&p_porady=' . ($page_porady ?? '');
};
?>
<ul class="pagination">
    <li>
        <?= $firstItemNumber ?> - <?= $lastItemNumber ?> ze <?= $total ?>
    </li>
</ul>
<ul class="pagination">
    <?php if (isset($previous)) { ?>
        <li class="page-item">
            <a class="page-link" href="<?= $urlFor($previous) ?>">
                <i class="fa fa-angle-double-left"></i>
            </a>
        </li>
    <?php } else { ?>
        <li class="page-item disabled">
            <a class="page-link" href="#">
                <i class="fa fa-angle-double-left"></i>
            </a>
        </li>
    <?php } ?>
    <?php foreach ($pagesInRange as $p) { ?>
        <?php if ($p !== $page) { ?>
            <li class="page-item">
                <a class="page-link" href="<?= $urlFor($p) ?>">
                    <?= $p; ?>
                </a>
            </li>
        <?php } else { ?>
            <li class="page-item active">
                <a class="page-link" href="#">
                    <?= $p ?>
                </a>
            </li>
        <?php } ?>
    <?php } ?>
    <?php if (isset($next)) { ?>
        <li class="page-item">
            <a class="page-link" href="<?= $urlFor($next) ?>">
                <i class="fa fa-angle-double-right"></i>
            </a>
        </li>
    <?php } else { ?>
        <li class="page-item disabled">
            <a class="page-link" href="#">
                <i class="fa fa-angle-double-right"></i>
            </a>
        </li>
    <?php } ?>
</ul>
