<?php
/** @var array|null $blockTriptip */
/** @var array|null $region */

$timeFormat = function (DateTime $date) use ($locale): string {
    return (new IntlDateFormatter($locale, IntlDateFormatter::NONE, IntlDateFormatter::SHORT))->format($date) ?: '';
};

$region_title = (isset($region) && $region && $region['url'] !== 'moravskoslezsky-kraj') ? ' - ' . $region['region'] : '';

?>

<?php if ($blockTriptip) { ?>
    <div class="container-fluid block-news bg-e2e5e9 mb-4-5">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h3 class="text-5 text-primary d-inline-block line-height-3 my-3 my-md-4">
                        <a class="text-primary" href="<?= $view->path('triptip') ?>">
                            Kam vyrazit<?= $region_title ?>
                        </a>
                    </h3>
                    <a class="pull-right text-primary text-3 font-weight-semibold d-none d-sm-block mt-4" href="<?= $view->path('triptip') ?>">
                        více&nbsp;<i class="fas fa-chevron-right text-1"></i>
                    </a>
                </div>
            </div>
        </div>
        <!-- Pokud dojde k obnově carouselu (nefunguje pak sticky na pravé bloky), tak oddělat container>row>col níže, nechat jen carousel>article -->
        <!--<div class="container owl-carousel owl-theme stage-margin nav-style-1 d-flex" data-plugin-options="{'items': 4, 'margin': 30, 'loop': false, 'nav': true, 'dots': false, 'stagePadding': 40}">-->
        <div class="container">
            <div class="row">
                <?php for ($i = 0, $iMax = count($blockTriptip); $i < $iMax; $i++) { ?>
                    <?php
                        $hide_on_mobile = '';
                        if ($i >= 3) {
                            $hide_on_mobile = 'd-none d-lg-block';
                        } else if ($i >= 2) {
                            $hide_on_mobile = 'd-none d-md-block';
                        }
                    ?>
                    <div class="col-lg-3 col-md-4 col-6 <?= $hide_on_mobile ?>">
                        <?php if ($blockTriptip[$i]['picture']) { ?>
                            <article class="">
                                <div class="row mb-4">
                                    <div class="col-12 d-flex mb-2-2-3">
                                        <div class="img-thumbnail">
                                            <a class="" href="<?= $blockTriptip[$i]['article_url'] ?>" title="<?= $blockTriptip[$i]['title'] ?>">
                                                <span class="thumb-info thumb-info-lighten">
                                                    <span class="thumb-info-wrapper">
                                                        <img src="<?= $blockTriptip[$i]['picture'] ?>" class="img-fluid" alt="<?= $blockTriptip[$i]['title'] ?>">
                                                    </span>
                                                </span>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <h2 class="mb-1">
                                            <a class="" href="<?= $blockTriptip[$i]['article_url'] ?>" title="<?= $blockTriptip[$i]['title'] ?>">
                                                <?= $blockTriptip[$i]['title'] ?>
                                            </a>
                                        </h2>
                                        <div class="text-2 text-454647 font-weight-semibold line-height-5">
                                            <?php $formatter = new IntlDateFormatter($locale, IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, null, null, 'd.M.'); ?>
                                            <span class="d-inline-flex">
                                                <?php $dateFrom = new DateTime($blockTriptip[$i]['term_from']); ?>
                                                <?php $today = new DateTime(); ?>
                                                <?php if ($today->format('Y-m-d') == $dateFrom->format('Y-m-d')) { ?>
                                                    Dnes
                                                <?php } else { ?>
                                                    <?php $today->modify('+1 day'); ?>
                                                    <?php if ($today->format('Y-m-d') == $dateFrom->format('Y-m-d')) { ?>
                                                        Zítra
                                                    <?php } else { ?>
                                                        <?= $formatter->format($dateFrom); ?>
                                                    <?php } ?>
                                                <?php } ?>
                                            </span>
                                            <span class="d-inline-flex">
                                                <?= ' ' . $timeFormat(new DateTime($blockTriptip[$i]['term_from'])); ?>
                                                <?php if ($blockTriptip[$i]['term_to']) { ?>
                                                    <?php $dateTo = new DateTime($blockTriptip[$i]['term_to']); ?>
                                                    <?php if ($dateFrom->format('Y-m-d') == $dateTo->format('Y-m-d')) { ?>
                                                        - <?= $timeFormat(new DateTime($blockTriptip[$i]['term_to'])); ?>
                                                    <?php } else { ?>
                                                        - <?= $formatter->format($dateTo); ?>
                                                        <?= $timeFormat(new DateTime($blockTriptip[$i]['term_to'])); ?>
                                                    <?php } ?>
                                                <?php } ?>
                                            </span><!--
                                            --><span class="d-inline-flex">
                                                <?= ',&nbsp;' . $blockTriptip[$i]['city']; ?>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </article>
                        <?php } else { ?>
                            <article class="">
                                <div class="row mb-4">
                                    <div class="col-12">
                                        <div class="">
                                            <h2 class="mb-1">
                                                <a class="" href="<?= $blockTriptip[$i]['article_url'] ?>" title="<?= $blockTriptip[$i]['title'] ?>">
                                                    <?= $blockTriptip[$i]['title'] ?>
                                                </a>
                                            </h2>
                                            <div class="text-2 text-454647 font-weight-semibold line-height-5">
                                                <?php $formatter = new IntlDateFormatter($locale, IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, null, null, 'd.M.'); ?>
                                                <span class="d-inline-flex">
                                                    <?php $dateFrom = new DateTime($blockTriptip[$i]['term_from']); ?>
                                                    <?php $today = new DateTime(); ?>
                                                    <?php if ($today->format('Y-m-d') == $dateFrom->format('Y-m-d')) { ?>
                                                        Dnes
                                                    <?php } else { ?>
                                                        <?php $today->modify('+1 day'); ?>
                                                        <?php if ($today->format('Y-m-d') == $dateFrom->format('Y-m-d')) { ?>
                                                            Zítra
                                                        <?php } else { ?>
                                                            <?= $formatter->format($dateFrom); ?>
                                                        <?php } ?>
                                                    <?php } ?>
                                                </span>
                                                <span class="d-inline-flex">
                                                    <?= ' ' . $timeFormat(new DateTime($blockTriptip[$i]['term_from'])); ?>
                                                    <?php if ($blockTriptip[$i]['term_to']) { ?>
                                                        <?php $dateTo = new DateTime($blockTriptip[$i]['term_to']); ?>
                                                        <?php if ($dateFrom->format('Y-m-d') == $dateTo->format('Y-m-d')) { ?>
                                                            - <?= $timeFormat(new DateTime($blockTriptip[$i]['term_to'])); ?>
                                                        <?php } else { ?>
                                                            - <?= $formatter->format($dateTo); ?>
                                                            <?= $timeFormat(new DateTime($blockTriptip[$i]['term_to'])); ?>
                                                        <?php } ?>
                                                    <?php } ?>
                                                </span><!--
                                                --><span class="d-inline-flex">
                                                    <?= ',&nbsp;' . $blockTriptip[$i]['city']; ?>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </article>
                        <?php } ?>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
<?php } else { ?>
    <hr class="solid">
<?php } ?>
