<?php
/** @var \App\Application\View\ViewHelper $view */

// Deaktivace komerčních článků pro seznam.cz
$view->addInlineScript(
    '
        var sspScript = document.getElementById("ssp-script");
        sspScript.addEventListener("load", function() {
            if (sssp.displaySeznamAds()) {
                $(".removeFromSeznam").hide();
            }
        });
        '
);

?>

<div class="removeFromSeznam">
    <?php if ($pr) { ?>
        <h2 class="text-primary text-4-5 mb-4">
            <a class="text-primary" href="<?= $view->path('news_pr') ?>" title="Komerční sdělení">
                Komerční sdělení
            </a>
            <a class="pull-right text-primary text-2 d-none d-sm-block" href="<?= $view->path('news_pr') ?>" title="Komerční sdělení">
                <small>
                    více
                    <i class="fas fa-chevron-right text-1"></i>
                </small>
            </a>
        </h2>
        <?php // Pokud je PR článků méně nebo rovno 5, zobrazíme je v kuse bez reklamy ?>
        <?php if (count($pr) <= 5) { ?>

            <?php for ($i = 0, $iMax = count($pr); $i < $iMax; $i++) { ?>
                <article class="">
                    <div class="row mb-3 mb-md-4">
                        <?php  if ($pr[$i]['picture']) { ?>
                            <div class="col-5 pe-2 pe-md-3">
                                <div class="">
                                    <a class="" href="<?= $view->path('news_pr_article', ['article_id' => $pr[$i]['article_id'], 'article_url' => $pr[$i]['article_url']]) ?>" title="<?= $pr[$i]['title'] ?>">
                                        <span class="thumb-info thumb-info-lighten">
                                            <span class="thumb-info-wrapper">
                                                <img src="<?= $pr[$i]['picture'] ?>" class="img-fluid" alt="<?= $pr[$i]['title'] ?>">
                                                <?php if (strpos($pr[$i]['picture'], '/videos/') !== false) { ?>
                                                    <span class="thumb-info-action">
                                                        <span class="thumb-info-action-icon">
                                                            <i class="fas fa-play"></i>
                                                            <span class="player_duration"><?= $pr[$i]['duration'] ? gmdate("i:s", $pr[$i]['duration']) : ''; ?></span>
                                                        </span>
                                                    </span>
                                                <?php } ?>
                                            </span>
                                        </span>
                                    </a>
                                </div>
                            </div>
                            <div class="col-7 ps-1 pe-3">
                                <h3 class="h2-size line-height-2 mb-1">
                                    <a class="text-secondary font-weight-semibold text-1" href="<?= $view->path('news_pr_article', ['article_id' => $pr[$i]['article_id'], 'article_url' => $pr[$i]['article_url']]) ?>" title="<?= $pr[$i]['title'] ?>">
                                        <?= $pr[$i]['title'] ?>
                                    </a>
                                </h3>
                                <div class="d-none d-sm-block">
                                    <p class="block-truncate block-truncate-2 line-height-6 mb-0">
                                        <?= $pr[$i]['anotation']; ?>
                                    </p>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </article>
            <?php } ?>

        <?php // Pokud je PR článků více než 5, zobrazíme je s reklamou ?>
        <?php } else { ?>

            <?php // První část PR článků ?>
            <?php for ($i = 0; $i < 3; $i++) { ?>
                <article class="">
                    <div class="row mb-3 mb-md-4">
                        <?php  if ($pr[$i]['picture']) { ?>
                            <div class="col-5 pe-2 pe-md-3">
                                <div class="">
                                    <a class="" href="<?= $view->path('news_pr_article', ['article_id' => $pr[$i]['article_id'], 'article_url' => $pr[$i]['article_url']]) ?>" title="<?= $pr[$i]['title'] ?>">
                                        <span class="thumb-info thumb-info-lighten">
                                            <span class="thumb-info-wrapper">
                                                <img src="<?= $pr[$i]['picture'] ?>" class="img-fluid" alt="<?= $pr[$i]['title'] ?>">
                                                <?php if (strpos($pr[$i]['picture'], '/videos/') !== false) { ?>
                                                    <span class="thumb-info-action">
                                                        <span class="thumb-info-action-icon">
                                                            <i class="fas fa-play"></i>
                                                            <span class="player_duration"><?= $pr[$i]['duration'] ? gmdate("i:s", $pr[$i]['duration']) : ''; ?></span>
                                                        </span>
                                                    </span>
                                                <?php } ?>
                                            </span>
                                        </span>
                                    </a>
                                </div>
                            </div>
                            <div class="col-7 ps-1 pe-3">
                                <h3 class="h2-size line-height-2 mb-1">
                                    <a class="text-secondary font-weight-semibold text-1" href="<?= $view->path('news_pr_article', ['article_id' => $pr[$i]['article_id'], 'article_url' => $pr[$i]['article_url']]) ?>" title="<?= $pr[$i]['title'] ?>">
                                        <?= $pr[$i]['title'] ?>
                                    </a>
                                </h3>
                                <div class="d-none d-sm-block">
                                    <p class="block-truncate block-truncate-2 line-height-6 mb-0">
                                        <?= $pr[$i]['anotation']; ?>
                                    </p>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </article>
            <?php } ?>

            <?php // REKLAMA ?>
            <?= $view->include('banner/web/partial/ads/rectangle', ['bannerRectangle' => $bannerRectangle ?? null]) ?>
            <br />

            <?php // Poslední část PR článků ?>
            <?php for ($i = 3, $iMax = count($pr); $i < $iMax; $i++) { ?>
                <article class="">
                    <div class="row mb-3 mb-md-4">
                        <?php  if ($pr[$i]['picture']) { ?>
                            <div class="col-5 pe-2 pe-md-3">
                                <div class="img-thumbnail">
                                    <a class="" href="<?= $view->path('news_pr_article', ['article_id' => $pr[$i]['article_id'], 'article_url' => $pr[$i]['article_url']]) ?>" title="<?= $pr[$i]['title'] ?>">
                                        <span class="thumb-info thumb-info-lighten">
                                            <span class="thumb-info-wrapper">
                                                <img src="<?= $pr[$i]['picture'] ?>" alt="<?= $pr[$i]['title'] ?>" class="img-fluid" />
                                                <?php if (strpos($pr[$i]['picture'], '/videos/') !== false) { ?>
                                                    <span class="thumb-info-action">
                                                        <span class="thumb-info-action-icon">
                                                            <i class="fas fa-play"></i>
                                                            <span class="player_duration"><?= $pr[$i]['duration'] ? gmdate("i:s", $pr[$i]['duration']) : ''; ?></span>
                                                        </span>
                                                    </span>
                                                <?php } ?>
                                            </span>
                                        </span>
                                    </a>
                                </div>
                            </div>
                            <div class="col-7 ps-1 pe-3">
                                <h3 class="h2-size line-height-2 mb-1">
                                    <a class="text-secondary font-weight-semibold text-1" href="<?= $view->path('news_pr_article', ['article_id' => $pr[$i]['article_id'], 'article_url' => $pr[$i]['article_url']]) ?>" title="<?= $pr[$i]['title'] ?>">
                                        <?= $pr[$i]['title'] ?>
                                    </a>
                                </h3>
                                <div class="d-none d-sm-block">
                                    <p class="block-truncate block-truncate-2 line-height-6 mb-0">
                                        <?= $pr[$i]['anotation']; ?>
                                    </p>
                                </div>
                            </div>
                        <?php }?>
                    </div>
                </article>
            <?php } ?>

        <?php } ?>

        <a class="d-flex justify-content-end" href="<?= $view->path('news_pr') ?>" title="Více">
            <small>
                Více
                <i class="fa fa-angle-double-right"></i>
            </small>
        </a>
    <?php } ?>
</div>
