<?php
/** @var \App\Application\View\ViewHelper $view */
?>

<div class="col-sm">
    <section class="card card-featured-top card-featured-primary mb-4">
        <div class="card-body">
            <div class="widget-summary">
                <div class="widget-summary-col widget-summary-col-icon">
                    <div class="summary-icon bg-primary hvr-grow">
                        <i class="fa fa-file-alt"></i>
                    </div>
                </div>
                <div class="widget-summary-col">
                    <div class="summary">
                        <h4 class="title text-nowrap">Stránky</h4>
                        <div class="info text-nowrap">
                            <strong class="amount"><?= $countPage ?></strong>
                            <span class="text-primary">(<?= $countPageActive ?> aktivních)</span>
                        </div>
                    </div>
                    <div class="summary-footer">
                        <a href="<?= $view->path('admin_page_list') ?>" class="text-muted text-uppercase">
                            <i class="fa fa-fw fa-ellipsis-v"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
