<?php
/** @var \App\Application\View\ViewHelper $view */

$keywords = [
    'default'              =>  'kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'albrechtice'          =>  'albrechtice, karvinsko, okres karviná, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'terlicko'             =>  'těrlicko, karvinsko, okres karviná, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'bruntal'              =>  'bruntál, okres bruntál, bruntálsko, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'krnov'                =>  'krnov, okres bruntál, bruntálsko, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'frydek-mistek'        =>  'frýdek-místek, okres frýdek-místek, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'opava'                =>  'opava, opavsko, okres opava, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'ostrava-mesto'        =>  'ostrava, ostravsko, okres ostrava, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'ostrava-jih'          =>  'ostrava-jih, ostravsko, okres ostrava, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'ostrava-marianske-hory'=> 'ostrava-mariánské-hory, ostravsko, okres ostrava, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'ostrava-centrum'      =>  'ostrava-centrum, ostravsko, okres ostrava, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'karvina'              =>  'karviná, karvinsko, okres karviná, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'novy-jicin'           =>  'nový jičín, novojičínsko, okres nový jičín, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'cely-ms-kraj'         =>  'moravskoslezský kraj, moravskoslezsko, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'havirov'              =>  'havířov, karvinsko, okres karviná, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'ludgerovice'          =>  'ludgeřovice, opavsko, okres opava, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'orlova'               =>  'orlová, karvinsko, okres karviná, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'ostatni'              =>  'regionální kam vyrazit, zprávy, reportáže, polar, tv, televize, moravskoslezský kraj',
    'stonava'              =>  'stonava, karvinsko, okres karviná, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'urad-ms-kraje'        =>  'úřad ms kraje',
    'celadna'              =>  'čeladná, frýdeckomístecko, okres frýdek-místek, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'frydlant-nad-ostravici' =>  'fráýdlant nad ostravicí, frýdeckomístecko, okres frýdek-místek, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'palkovice'              =>  'palkovice, frýdeckomístecko, okres frýdek-místek, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'horni-sucha'          =>  'horní suchá, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'ostrava-poruba'       =>  'ostrava poruba, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'slezska-ostrava'      =>  'slezská ostrava, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'rychvald'             =>  'rychvald, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'cesky-tesin'          =>  'český těšín, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'jablunkov'            =>  'jablůnkov, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'nosovice'             =>  'nošovice, kam vyrazit, zprávy, reportáže, polar, tv, televize',
    'studenka'             =>  'studénka, kam vyrazit, zprávy, reportáže, polar, tv, televize',
];
$descriptions = [
    'default'              =>  'Sledujte akce z TV POLAR online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'albrechtice'          =>  'Sledujte akce z Albrechtic online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'terlicko'             =>  'Sledujte akce z Těrlicka online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'bruntal'              =>  'Sledujte akce z Bruntálu online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'krnov'                =>  'Sledujte akce z Krnova online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'frydek-mistek'        =>  'Sledujte akce z Frýdku-Místku online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'opava'                =>  'Sledujte akce z Opavy online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'ostrava-mesto'        =>  'Sledujte akce z Ostravy online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'ostrava-jih'          =>  'Sledujte akce z Ostravy-Jih online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'ostrava-marianske-hory'=> 'Sledujte akce z Ostravy-Mariánských hor online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'ostrava-centrum'      =>  'Sledujte akce z Ostravy-Centra online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'karvina'              =>  'Sledujte akce z Karviné online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'novy-jicin'           =>  'Sledujte akce z Nového Jičína online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'cely-ms-kraj'         =>  'Sledujte akce z Moravskoslezského kraje online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'havirov'              =>  'Sledujte akce z Havířova online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'ludgerovice'          =>  'Sledujte akce z Ludgeřovic online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'orlova'               =>  'Sledujte akce z Orlové online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'ostatni'              =>  'Sledujte akce online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'stonava'              =>  'Sledujte akce ze Stonavy online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'urad-ms-kraje'        =>  'Sledujte akce z Úřadu moravskoslezského kraje online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'celadna'              =>  'Sledujte akce z Čeladné online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'frydlant-nad-ostravici' =>  'Sledujte akce z Frýdlantu nad Ostravicí online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'palkovice'              =>  'Sledujte akce z Palkovic online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'horni-sucha'          =>  'Sledujte akce z Horní Suché online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'ostrava-poruba'       =>  'Sledujte akce z Palkovic online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'slezska-ostrava'      =>  'Sledujte akce z Ostravy Poruby online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'rychvald'             =>  'Sledujte akce z Rychvaldu online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'cesky-tesin'          =>  'Sledujte akce z Českého Těšína online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'jablunkov'            =>  'Sledujte akce z Jablůnkova online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'nosovice'             =>  'Sledujte akce z Nošovic online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
    'studenka'             =>  'Sledujte akce ze Studénky online. Denně Vám přinášíme aktuální zprávy a mnoho dalšího.',
];

$city_url = $city['url'];

// HeadTitle
$view->setTitle('Kam vyrazit ' . $city['city']);

// HeadMeta
$view->addMeta('description', $descriptions[$city_url] ?? $descriptions['default']);
$view->addMeta('keywords', $keywords[$city_url] ?? $keywords['default']);

// META pro Facebook
$currentUrl = $this->currentUrl ?? '';
$view->addOgMeta('og:title', 'Kam vyrazit ' . $city['city'] . ' | POLAR');
$view->addOgMeta('og:description', $descriptions[$city_url] ?? $descriptions['default']);
$view->addOgMeta('og:url', $currentUrl);
$view->addOgMeta('og:type', 'website');
$view->addOgMeta('og:image', 'https://polar.cz/img/web/layout/microformat.png');
$view->addOgMeta('og:image:secure_url', 'https://polar.cz/img/web/layout/microformat.png');
$view->addOgMeta('og:image:width', '1920');
$view->addOgMeta('og:image:height', '1080');

    $view->addInlineScript(
    	    'function initData(){
                $("#calendar ul li a").not(".disabled").click(function(){
                    var hash = $(this).attr("href").substring(1);
    	            var today = new Date();
    	            if ((hash) && hash < today.toISOString().substring(0, 10)) window.location.href = "/kam-vyrazit/'.$region['url'].'/'.$city['url'].'";
                    $.post("' . $view->path('news_triptip_get_triptip_list') . '",
                        {
                            date: hash,
                            region_id: null,
                            city_id: '.$city['id'].',
                        },
                        function(json) {
            				$("#calendar").html(json.calendar);
            				$("#list").html(json.content);
    	                    initData();
                    	    $("#nextEvents").click(function(){
                                $("section.section-kamvyrazit .row.hide").removeClass("hide");
            	                $(this).remove();
                            });
                        },
                        "json"
                    );
                });
            }
    	    var hash = window.location.hash.substring(1);
    	    var today = new Date();
    	    if ((hash) && hash < today.toISOString().substring(0, 10)) window.location.href = "/kam-vyrazit/'.$region['url'].'/'.$city['url'].'";
            $.post("' . $view->path('news_triptip_get_triptip_list') . '",
                {
                    date: hash,
                    region_id: null,
                    city_id: '.$city['id'].',
                },
                function(json) {
    				$("#calendar").html(json.calendar);
    				$("#list").html(json.content);
    	            initData();
            	    $("#nextEvents").click(function(){
                        $("section.section-kamvyrazit .row.hide").removeClass("hide");
    	                $(this).remove();
                    });
                },
                "json"
            );
    	    '
    	);

    // Ticker + Crawl JS
    $view->addInlineScript(
    	    '// Ticker
            getTickerData();
            interval = startTicker();
            // Crawl
            getCrawlData();'
    	);

    /** @var $articles */
    /** @var $exhibitions */

    $dateFormat = function(DateTime $date, int $dateType, int $timeType, string $locale): string {
        return (new IntlDateFormatter($locale, $dateType, $timeType))->format($date) ?: '';
    };

?>

<section class="page-header page-header-modern bg-color-light-scale-1 page-header-sm mb-0 mb-lg-4">

    <div class="container">
        <div class="row">
            <div class="col-md-12 align-self-center order-1">
                <?= $view->include('application/navigation/breadcrumb') ?>
            </div>
        </div>
    </div>
</section>

<!--<div class="container">
    <div class="featured-box featured-box-secondary featured-box-text-center mt-none">
        <div class="box-content text-color-secondary">
            <strong>
                VZHLEDEM K&nbsp;AKTUÁLNÍ SITUACI OHLEDNĚ KORONAVIRU NEMUSÍ BÝT INFORMACE V&nbsp;RUBRICE "KAM VYRAZIT" AKTUÁLNÍ.<br>KONÁNÍ AKCE PROSÍM VŽDY OVĚŘUJTE U&nbsp;ORGANIZÁTORŮ AKCE.
            </strong>
        </div>
    </div>
</div>-->
<div class="container mb-5">
    <div class="sticky-container">
        <div class="row">
            <div class="col-12">
                <div id="crawl" class="mb-2 hide">
                    <div id="crawlIcon">
                        Mimořádná zpráva:
                    </div>
                    <div class="crawl-container">
                        <div>
                            Načítám...
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-lg-8 mb-5 mb-lg-2">
                <div id="ticker" class="mb-4">
                    <div id="tickerIcon" class="">
                        <!--<i class="fa fa-fw fa-info text-light"></i>-->
                    </div>
                    <div class="ticker-container">
                        <ul>
                            <div class="ticker-active">
                                <li>
                                    <span>
                                        Načítám...
                                    </span>
                                </li>
                            </div>
                        </ul>>
                    </div>
                </div>
                <section class="section-kamvyrazit">
        			<?php if ($articles) {?>
        				<div class="featured-box featured-box-primary featured-box-text-start">
                            <div class="box-content text-start px-2 pt-3 pb-3">
                                <div class="owl-carousel show-nav-hover mb-0" data-plugin-options='{"responsive": {"0": {"items": 1}, "479": {"items": 2}, "768": {"items": 3}, "979": {"items": 3}, "1199": {"items": 3}}, "margin": 15, "nav": true, "dots": false, "autoplay": true, "autoplayTimeout": 5000, "loop": true}'>
                                    <?php foreach ($articles as $article) {?>
                                        <?php if ($article['image']) {?>
                                            <div class="ps-1 pe-1">
                                                <div class="img-thumbnail">
                                                    <a href="<?= $article['url'];?>" title="<?= $article['title'];?>">
                                                        <img src="<?= $article['image'];?>" class="img-fluid" alt="" />
                                                    </a>
                                                </div>
                                                <h2>
                                                    <a href="<?= $article['url'];?>" title="<?= $article['title'];?>">
                                                        <?= $article['title'];?>
                                                    </a>
                                                </h2>
                                                <div class="">
                                                    <?php $formatter = new IntlDateFormatter($locale, IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, null, null, 'dd.MM.');?>
                                                    <span>
                                                        <i class="fa fa-fw fa-calendar text-color-primary"></i>
                                                        <?php $dateFrom = new DateTime($article['term_from']);?>
                                                        <?php $today = new DateTime();?>
                                                        <?php if ($today->format('Y-m-d') == $dateFrom->format('Y-m-d')) {?>
                                                            Dnes
                                                        <?php }else{?>
                                                            <?php $today->modify('+1 day');?>
                                                            <?php if ($today->format('Y-m-d') == $dateFrom->format('Y-m-d')) {?>
                                                                Zítra
                                                            <?php }else{?>
                                                                <?= $formatter->format($dateFrom);?>
                                                            <?php }?>
                                                        <?php }?>
                                                    </span>
                                                    <span>
                                                        <?= ' '.$dateFormat(new DateTime($article['term_from']), IntlDateFormatter::NONE, IntlDateFormatter::SHORT, $locale);?>
                                                        <?php if ($article['term_to']) {?>
                                                            <?php $dateTo = new DateTime($article['term_to']);?>
                                                            <?php if ($dateFrom->format('Y-m-d') == $dateTo->format('Y-m-d')) {?>
                                                                - <?= $dateFormat(new DateTime($article['term_to']), IntlDateFormatter::NONE, IntlDateFormatter::SHORT, $locale);?>
                                                            <?php }else{?>
                                                                - <?= $formatter->format($dateTo);?>
                                                                <?= $dateFormat(new DateTime($article['term_to']), IntlDateFormatter::NONE, IntlDateFormatter::SHORT, $locale);?>
                                                            <?php }?>
                                                        <?php }?>
                                                    </span>

                                                    <div class="mt-1">
                                                        <span>
                                                            <i class="fa fa-fw fa-map-pin text-primary"></i>
                                                            <a href="<?= $view->path('news_triptip_city', ['url' => $article['region_url'], 'city_url' => $article['city_url']]);?>" title="">
                                                                <?= $article['city'];?></a>, <?= $article['place'];?>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php }?>
                                    <?php }?>
                                </div>
                            </div>
                        </div>
        			<?php }?>

        			<div id="calendar" class="my-4">

                    </div>

                    <div id="list">
                        Čekejte prosím...
                    </div>
    			</section>
    			
            </div>
            
            <div class="col-12 col-lg-4 order-0 order-lg-1">

                <!-- Výstavy -->
                <?= $view->include('news/web/triptip/partial/exhibitions', ['exhibitions' => $exhibitions]) ?>

                <?php // REKLAMA ?>
                <br /><?= $view->include('banner/partial/ads/article-right-bottom') ?>
        			
            </div>
            
        </div>
    </div>
</div>
