<?php
/** @var \App\Application\View\ViewHelper $view */
?>

<div class="row">
    <div class="col-lg-3">

    </div>
    <div class="col-lg-9">
        <section class="card card-primary">
            <header class="card-header">
                <div class="card-actions">
                    <?php if (!empty($errors)) { ?>
                        <span class="badge badge-danger">
                            Neuloženo
                        </span>
                    <?php } ?>
                </div>
                <h2 class="card-title">
                    Upravit kameru
                </h2>
            </header>
            <?= $view->include('camera/admin/cameraForm', [
                'formAction' => $view->path('admin_camera_edit', ['id' => $id]),
                'post'       => $post,
                'errors'     => $errors,
            ]) ?>
        </section>
    </div>
</div>
