<?php
/*
 * @project polar
 * @author Rostislav Greipel
 * @link https://rogr.cz
 * @copyright (c) 2011 - 2021 ROGR All Rights Reserved
 * @license https://rogr.cz/license/eula EULA License
 */
?>

<div class="row">
    <div class="col-lg-6">
        <div class="row">
            <?= $view->include('camera/admin/partial/dashboard/widget', ['countCamera' => $countCamera ?? 0]) ?>
        </div>
    </div>
    <div class="col-lg-6">
        <section class="card mb-4">
            <header class="card-header">
                <div class="card-header-icon bg-primary">
                    <i class="fa fa-camera"></i>
                </div>
            </header>
            <div class="card-body text-center">
                <h3 class="font-weight-semibold mt-3 text-center">
                    Kamery
                </h3>
                <p class="text-center">
                    TV Polar
                </p>
            </div>
        </section>
        <section class="card card-featured card-featured-primary mt-0">
            <header class="card-header">
                <div class="card-actions pull-right mb-0">
                    <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
                    <a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>
                </div>
                <h2 class="card-title">
                    Historie změn
                </h2>
            </header>
            <div class="card-body">
                <?= $view->include('camera/admin/partial/changelog') ?>
            </div>
        </section>
    </div>
</div>
