<?php
/** @var \App\Application\View\ViewHelper $view */

$identity = $identity ?? null;

$view->addHeadLink('stylesheet', $view->asset('vendor/admin/bootstrap-table/css/bootstrap-table.min.css'));
$view->addHeadLink('stylesheet', $view->asset('vendor/admin/bootstrap-table/extension/reorder-rows/css/reorder-rows.min.css'));
$view->addBodyScript($view->asset('vendor/admin/table-dnd/js/table-dnd.min.js'));
$view->addBodyScript($view->asset('vendor/admin/bootstrap-table/js/bootstrap-table.min.js'));
$view->addBodyScript($view->asset('vendor/admin/bootstrap-table/js/locale/' . $locale . '.min.js'));
$view->addBodyScript($view->asset('vendor/admin/bootstrap-table/extension/cookie/js/cookie.min.js'));
$view->addBodyScript($view->asset('vendor/admin/bootstrap-table/extension/mobile/js/mobile.min.js'));
$view->addBodyScript($view->asset('vendor/admin/bootstrap-table/extension/reorder-rows/js/reorder-rows.min.js'));
$view->addBodyScript($view->asset('vendor/admin/moment/js/moment.min.js'));
$view->addBodyScript($view->asset('vendor/admin/moment/js/locale/' . $locale . '.min.js'));

// Smazání kamery
$view->addInlineScript(
    '$("#btblCamera").on("post-body.bs.table", function (e, data) {
        $(".btblBtnDeleteCamera").unbind("click").bind("click", function() {
            var id = $(this).data("video-id");
            $.post("' . $view->path('admin_camera_json_list_get_camera') . '",
                {id: id},
                function(json) {
                    if (json.success) {
                        $("#modalDanger .card-title").html("Smazat kameru");
                        $("#modalDanger .modal-text h4").html("Opravdu chcete smazat kameru?<br><strong>\"" + json.camera.title + "\"</strong>");
                        $("#modalDanger .modal-text p").html("Všechny závislosti budou smazány. Tuto akci nelze vrátit!");
                        var btnConfirm = $("#modalDanger .card-footer button.modal-confirm");

                        $.magnificPopup.open({
                            items: {src: "#modalDanger"},
                            type: "inline",
                            fixedContentPos: false,
                            fixedBgPos: true,
                            overflowY: "auto",
                            closeBtnInside: true,
                            preloader: false,
                            midClick: true,
                            removalDelay: 300,
                            mainClass: "my-mfp-slide-bottom",
                            modal: true,
                            callbacks: {
                                open: function() {
                                    btnConfirm.unbind("click").click(function(e){
                                        e.preventDefault();
                                        $.post("' . $view->path('admin_camera_json_write_delete') . '",
                                            {id: id},
                                            function(json) {
                                                if (json.success) {
                                                    var notice = new PNotify({
                                                        title: "Uloženo",
                                                        text: "Kamera byla smazána!",
                                                        type: "success",
                                                        addclass: "click-2-close",
                                                        buttons: {sticker: false}
                                                    });
                                                    $("#btblCamera").bootstrapTable("refresh", {"silent": true});
                                                } else {
                                                    var notice = new PNotify({
                                                        title: "Chyba",
                                                        text: "Kameru se nepodařilo smazat!",
                                                        type: "error",
                                                        addclass: "click-2-close",
                                                        buttons: {sticker: false}
                                                    });
                                                }
                                                $.magnificPopup.close();
                                            },
                                            "json"
                                        );
                                    });
                                }
                            }
                        });
                    } else {
                        var notice = new PNotify({
                            title: "Chyba",
                            text: "Nepodařilo se načíst informace o kameře!",
                            type: "error",
                            addclass: "click-2-close",
                            buttons: {sticker: false}
                        });
                        $.magnificPopup.close();
                        $("#btblCamera").bootstrapTable("refresh", {"silent": true});
                    }
                },
                "json"
            );
        });
    });'
);

// Řazení kamer
$view->addInlineScript(
    '$("#btblCamera").on("reorder-row.bs.table", function (e, data) {
            $.post("' . $view->path('admin_camera_json_write_set_order') . '",
            {data: data},
            function(json) {
                var notice = new PNotify({
                    title: "Uloženo",
                    text: "Pořadí kamer bylo změněno!",
                    type: "success",
                    addclass: "click-2-close",
                    buttons: {sticker: false}
                });
                $("#btblCamera").bootstrapTable("refresh", {silent: true});
            },
            "json"
        );
    });'
);
?>
<div id="toolbar" class="btn-group">
    <a href="<?= $view->path('admin_camera_add') ?>" class="btn btn-primary">
        <i class="fa fa-fw fa-plus"></i>
        <span class="hidden-sm hidden-xs">
            Přidat kameru
        </span>
    </a>
</div>
<table id="btblCamera"
       data-url="<?= $view->path('admin_camera_json_list_get_list') ?>"
       data-toggle="table"
       data-show-search-button="true"
       data-show-search-clear-button="true"
       data-valign="middle"
       data-sort-name="rank"
       data-sort-order="asc"
       data-toolbar="#toolbar"
       data-cookie-id-table="USER-<?= $identity ? $identity->getId() : '0' ?>-cameraTable"
       data-mobile-responsive="true"
       data-use-row-attr-func="true"
       data-reorderable-rows="true"
       data-drag-handle=">tbody>tr>td.rank"
       data-page-size="13">
    <thead>
    <tr>
        <th class="text-nowrap width-nowrap"
            data-formatter="optionsFormatter"
            data-align="center">
            <i class="fa fa-cogs" data-toggle="tooltip" data-placement="right" title="Možnosti"></i>
            <span class="d-sm-none">
                Možnosti
            </span>
        </th>
        <th data-field="id"
            class="text-nowrap width-nowrap"
            data-sortable="true"
            data-visible="false">
            ID
        </th>
        <th data-field="rank"
            class="text-nowrap width-nowrap cur-rank rank"
            data-formatter="rankFormatter"
            data-sortable="true"
            data-align="center">
            <i class="fa fa-sort" data-toggle="tooltip" data-placement="right" title="Pořadí"></i>
            <span class="d-sm-none">
                Pořadí
            </span>
        </th>
        <th data-field="title"
            class="text-truncate"
            data-sortable="true">
            Titulek
        </th>
        <th data-field="description"
            class="text-truncate"
            data-sortable="true">
            Popis
        </th>
    </tr>
    </thead>
</table>
<script>
    function optionsFormatter(value, row) {
        let url = "<?= $view->path('admin_camera_list') ?>/upravit";
        let data = '';
        data += '<div class="btn-group pb-sm-0 pb-2">';
        data += '<a href="' + url + '/' + row.id + '" class="btn btn-sm btn-success"><i class="fa fa-edit"></i> <span class="d-none">Upravit</span></a> ';
        data += '<button data-video-id="' + row.id + '" class="btblBtnDeleteCamera btn btn-sm btn-danger"><i class="fa fa-trash-alt"></i> <span class="d-none">Smazat</span></button>';
        data += '</div>';
        return data;
    }
    function rankFormatter(value) {
        return value + ' <i class="fa fa-fw fa-arrows-alt-v ml-1"></i>';
    }
</script>
<?= $view->include('admin/modal/danger') ?>
