<?php
/** @var \App\Application\View\ViewHelper $view */

$scheme = $scheme ?? 'dark';
?>

<div class="container py-2">
    <?php if ($message) { ?>
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="alert <?= $alert ?> alert-lg alert-dismissible mb-0" role="alert">
                    <?= $message ?>
                </div>
                <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
            </div>
        </div>
    <?php } ?>
</div>
