<?php
/** @var \App\Application\View\ViewHelper $view */
/** @var string|null $active  'zpravy'|'kandidati'|'obec' */
$active = $active ?? null;
?>
<nav class="">
	<ul class="nav nav-pills w-100">
		<li class="nav-item">
			<a class="nav-link text-4<?= $active === 'index' ? ' active' : '' ?>" href="<?= $view->path('election_2026') ?>">Volební zprávy</a>
		</li>
		<li class="nav-item">
			<a class="nav-link text-4<?= $active === 'kandidati' ? ' active' : '' ?>" href="<?= $view->path('election_2026_kandidati', ['okres' => 8106]) ?>">Kandidáti</a>
		</li>
		<li class="nav-item">
			<a class="nav-link text-4<?= $active === 'obec' ? ' active' : '' ?>" href="<?= $view->path('election_2026_obec', ['okres' => 8106]) ?>">Vaše obec</a>
		</li>
		<li class="nav-item dropdown">
			<a class="dropdown-item dropdown-toggle d-flex align-items-center text-4 nav-link" href="#" data-bs-toggle="dropdown">Archiv</a>
			<ul class="dropdown-menu">
				<li><a class="dropdown-item" href="<?= $view->path('election_2024') ?>">Krajské volby 2024</a></li>
				<li><a class="dropdown-item" href="<?= $view->path('election_2020_kresla') ?>">Krajské volby 2020</a></li>
			</ul>
		</li>
	</ul>
</nav>
