<?php

// Auto-generated Program Show navigation - DO NOT EDIT MANUALLY
// Generated: 2026-04-21 14:21:34

return [
	'submenu-dropdown' => [
		'show' => [
			'pages' => [
				[
					'id' => 'menuProgramShowWeb-1',
					'label' => 'Regionální zprávy POLAR',
					'route' => 'program_show_1',
					'visible' => 0,
					'order' => 2,
				],
				[
					'id' => 'menuProgramShowWeb-13',
					'label' => 'Host dne',
					'route' => 'program_show_13',
					'visible' => 0,
					'order' => 3,
				],
				[
					'id' => 'menuProgramShowWeb-168',
					'label' => 'Sportovec roku MS kraje 2025',
					'route' => 'program_show_168',
					'visible' => 0,
					'order' => 4,
				],
				[
					'id' => 'menuProgramShowWeb-11',
					'label' => 'Magazín TV medicína',
					'route' => 'program_show_11',
					'visible' => 0,
					'order' => 5,
				],
				[
					'id' => 'menuProgramShowWeb-12',
					'label' => 'Eko magazín',
					'route' => 'program_show_12',
					'visible' => 0,
					'order' => 6,
				],
				[
					'id' => 'menuProgramShowWeb-14',
					'label' => 'Sportovní studio',
					'route' => 'program_show_14',
					'visible' => 0,
					'order' => 7,
				],
				[
					'id' => 'menuProgramShowWeb-67',
					'label' => 'Magazín 112',
					'route' => 'program_show_67',
					'visible' => 0,
					'order' => 8,
				],
				[
					'id' => 'menuProgramShowWeb-78',
					'label' => 'Dopravní revue',
					'route' => 'program_show_78',
					'visible' => 0,
					'order' => 9,
				],
				[
					'id' => 'menuProgramShowWeb-40',
					'label' => 'Studuj u nás',
					'route' => 'program_show_40',
					'visible' => 0,
					'order' => 10,
				],
				[
					'id' => 'menuProgramShowWeb-90',
					'label' => 'Léta běží',
					'route' => 'program_show_90',
					'visible' => 0,
					'order' => 11,
				],
				[
					'id' => 'menuProgramShowWeb-105',
					'label' => 'Kulturní okénko',
					'route' => 'program_show_105',
					'visible' => 0,
					'order' => 12,
				],
				[
					'id' => 'menuProgramShowWeb-69',
					'label' => 'Kam vyrazit',
					'route' => 'program_show_69',
					'visible' => 0,
					'order' => 13,
				],
				[
					'id' => 'menuProgramShowWeb-118',
					'label' => 'Dejme dětem rodinu',
					'route' => 'program_show_118',
					'visible' => 0,
					'order' => 14,
				],
				[
					'id' => 'menuProgramShowWeb-162',
					'label' => 'Ostrava plus',
					'route' => 'program_show_162',
					'visible' => 0,
					'order' => 15,
				],
				[
					'id' => 'menuProgramShowWeb-154',
					'label' => 'Řemeslo má respekt',
					'route' => 'program_show_154',
					'visible' => 0,
					'order' => 16,
				],
				[
					'id' => 'menuProgramShowWeb-155',
					'label' => 'Moravskoslezský expres',
					'route' => 'program_show_155',
					'visible' => 0,
					'order' => 17,
				],
				[
					'id' => 'menuProgramShowWeb-56',
					'label' => 'Ostravské minuty',
					'route' => 'program_show_56',
					'visible' => 0,
					'order' => 18,
				],
				[
					'id' => 'menuProgramShowWeb-61',
					'label' => 'Expres Ostrava-Jih',
					'route' => 'program_show_61',
					'visible' => 0,
					'order' => 19,
				],
				[
					'id' => 'menuProgramShowWeb-107',
					'label' => 'Expres Ostrava-Poruba',
					'route' => 'program_show_107',
					'visible' => 0,
					'order' => 20,
				],
				[
					'id' => 'menuProgramShowWeb-109',
					'label' => 'Slezskoostravský expres',
					'route' => 'program_show_109',
					'visible' => 0,
					'order' => 21,
				],
				[
					'id' => 'menuProgramShowWeb-8',
					'label' => 'Karvinský expres',
					'route' => 'program_show_8',
					'visible' => 0,
					'order' => 22,
				],
				[
					'id' => 'menuProgramShowWeb-2',
					'label' => 'Havířovský expres',
					'route' => 'program_show_2',
					'visible' => 0,
					'order' => 23,
				],
				[
					'id' => 'menuProgramShowWeb-127',
					'label' => 'Havířovské otázky',
					'route' => 'program_show_127',
					'visible' => 0,
					'order' => 24,
				],
				[
					'id' => 'menuProgramShowWeb-7',
					'label' => 'Frýdeckomístecký expres',
					'route' => 'program_show_7',
					'visible' => 0,
					'order' => 25,
				],
				[
					'id' => 'menuProgramShowWeb-9',
					'label' => 'Novojičínský expres',
					'route' => 'program_show_9',
					'visible' => 0,
					'order' => 26,
				],
				[
					'id' => 'menuProgramShowWeb-27',
					'label' => 'Opavský expres',
					'route' => 'program_show_27',
					'visible' => 0,
					'order' => 27,
				],
				[
					'id' => 'menuProgramShowWeb-16',
					'label' => 'Stonavský expres',
					'route' => 'program_show_16',
					'visible' => 0,
					'order' => 28,
				],
				[
					'id' => 'menuProgramShowWeb-102',
					'label' => 'Expres Studénky',
					'route' => 'program_show_102',
					'visible' => 0,
					'order' => 29,
				],
				[
					'id' => 'menuProgramShowWeb-85',
					'label' => 'Jesenický expres',
					'route' => 'program_show_85',
					'visible' => 0,
					'order' => 30,
				],
				[
					'id' => 'menuProgramShowWeb-86',
					'label' => 'Beskydský expres',
					'route' => 'program_show_86',
					'visible' => 0,
					'order' => 31,
				],
				[
					'id' => 'menuProgramShowWeb-74',
					'label' => 'Miniexpres centra Ostravy',
					'route' => 'program_show_74',
					'visible' => 0,
					'order' => 32,
				],
				[
					'id' => 'menuProgramShowWeb-64',
					'label' => 'Bruntálský miniexpres',
					'route' => 'program_show_64',
					'visible' => 0,
					'order' => 33,
				],
				[
					'id' => 'menuProgramShowWeb-82',
					'label' => 'Frýdlantský miniexpres',
					'route' => 'program_show_82',
					'visible' => 0,
					'order' => 34,
				],
				[
					'id' => 'menuProgramShowWeb-114',
					'label' => 'Miniexpres Horní Suché',
					'route' => 'program_show_114',
					'visible' => 0,
					'order' => 35,
				],
				[
					'id' => 'menuProgramShowWeb-130',
					'label' => 'Orlovský miniexpres',
					'route' => 'program_show_130',
					'visible' => 0,
					'order' => 36,
				],
				[
					'id' => 'menuProgramShowWeb-55',
					'label' => 'Mariánskohorský miniexpres',
					'route' => 'program_show_55',
					'visible' => 0,
					'order' => 37,
				],
				[
					'id' => 'menuProgramShowWeb-88',
					'label' => 'Palkovický miniexpres',
					'route' => 'program_show_88',
					'visible' => 0,
					'order' => 38,
				],
				[
					'id' => 'menuProgramShowWeb-100',
					'label' => 'Rychvaldský miniexpres',
					'route' => 'program_show_100',
					'visible' => 0,
					'order' => 39,
				],
				[
					'id' => 'menuProgramShowWeb-160',
					'label' => 'Fulnecký miniexpres',
					'route' => 'program_show_160',
					'visible' => 0,
					'order' => 40,
				],
				[
					'id' => 'menuProgramShowWeb-125',
					'label' => 'Vítkovický miniexpres',
					'route' => 'program_show_125',
					'visible' => 0,
					'order' => 41,
				],
				[
					'id' => 'menuProgramShowWeb-158',
					'label' => 'Oderský miniexpres',
					'route' => 'program_show_158',
					'visible' => 0,
					'order' => 42,
				],
				[
					'id' => 'menuProgramShowWeb-57',
					'label' => 'Těrlický miniexpres',
					'route' => 'program_show_57',
					'visible' => 0,
					'order' => 43,
				],
				[
					'id' => 'menuProgramShowWeb-98',
					'label' => 'Čeladenský miniexpres',
					'route' => 'program_show_98',
					'visible' => 0,
					'order' => 44,
				],
				[
					'id' => 'menuProgramShowWeb-66',
					'label' => 'Albrechtický miniexpres',
					'route' => 'program_show_66',
					'visible' => 0,
					'order' => 45,
				],
				[
					'id' => 'menuProgramShowWeb-103',
					'label' => 'Jablunkovský miniexpres',
					'route' => 'program_show_103',
					'visible' => 0,
					'order' => 46,
				],
				[
					'id' => 'menuProgramShowWeb-163',
					'label' => 'Bílovecký miniexpres',
					'route' => 'program_show_163',
					'visible' => 0,
					'order' => 47,
				],
				[
					'id' => 'menuProgramShowWeb-164',
					'label' => 'Dětmarovický miniexpres',
					'route' => 'program_show_164',
					'visible' => 0,
					'order' => 48,
				],
				[
					'id' => 'menuProgramShowWeb-113',
					'label' => 'Nošovický miniexpres',
					'route' => 'program_show_113',
					'visible' => 0,
					'order' => 49,
				],
				[
					'id' => 'menuProgramShowWeb-165',
					'label' => 'Doberský miniexpres',
					'route' => 'program_show_165',
					'visible' => 0,
					'order' => 50,
				],
				[
					'id' => 'menuProgramShowWeb-167',
					'label' => 'Miniexpres Bašky',
					'route' => 'program_show_167',
					'visible' => 0,
					'order' => 51,
				],
				[
					'id' => 'menuProgramShowWeb-166',
					'label' => 'Paskovský miniexpres',
					'route' => 'program_show_166',
					'visible' => 0,
					'order' => 52,
				],
				[
					'id' => 'menuProgramShowWeb-129',
					'label' => 'Svinovský miniexpres',
					'route' => 'program_show_129',
					'visible' => 0,
					'order' => 54,
				],
				[
					'id' => 'menuProgramShowWeb-128',
					'label' => 'Miniexpres Dolní Lutyně',
					'route' => 'program_show_128',
					'visible' => 0,
					'order' => 55,
				],
				[
					'id' => 'menuProgramShowWeb-150',
					'label' => 'Janovický miniexpres',
					'route' => 'program_show_150',
					'visible' => 0,
					'order' => 56,
				],
				[
					'id' => 'menuProgramShowWeb-152',
					'label' => 'Miniexpres Návsí',
					'route' => 'program_show_152',
					'visible' => 0,
					'order' => 57,
				],
				[
					'id' => 'menuProgramShowWeb-77',
					'label' => 'Chytrý region',
					'route' => 'program_show_77',
					'visible' => 0,
					'order' => 62,
				],
				[
					'id' => 'menuProgramShowWeb-124',
					'label' => 'Manažeři v akci',
					'route' => 'program_show_124',
					'visible' => 0,
					'order' => 63,
				],
				[
					'id' => 'menuProgramShowWeb-126',
					'label' => 'Auto Moto Kolo',
					'route' => 'program_show_126',
					'visible' => 0,
					'order' => 64,
				],
				[
					'id' => 'menuProgramShowWeb-161',
					'label' => 'Volební studio 2025',
					'route' => 'program_show_161',
					'visible' => 0,
					'order' => 65,
				],
				[
					'id' => 'menuProgramShowWeb-153',
					'label' => 'Volební studio 2024',
					'route' => 'program_show_153',
					'visible' => 0,
					'order' => 66,
				],
				[
					'id' => 'menuProgramShowWeb-123',
					'label' => 'Volební studio 2022',
					'route' => 'program_show_123',
					'visible' => 0,
					'order' => 67,
				],
				[
					'id' => 'menuProgramShowWeb-119',
					'label' => 'Parlamentní volební studio',
					'route' => 'program_show_119',
					'visible' => 0,
					'order' => 68,
				],
				[
					'id' => 'menuProgramShowWeb-111',
					'label' => 'Volební studio',
					'route' => 'program_show_111',
					'visible' => 0,
					'order' => 69,
				],
				[
					'id' => 'menuProgramShowWeb-96',
					'label' => 'Představujeme senátory',
					'route' => 'program_show_96',
					'visible' => 0,
					'order' => 71,
				],
				[
					'id' => 'menuProgramShowWeb-5',
					'label' => 'Malujeme pohádku',
					'route' => 'program_show_5',
					'visible' => 0,
					'order' => 74,
				],
				[
					'id' => 'menuProgramShowWeb-23',
					'label' => 'Baby English',
					'route' => 'program_show_23',
					'visible' => 0,
					'order' => 75,
				],
				[
					'id' => 'menuProgramShowWeb-42',
					'label' => 'Oči naší divočiny',
					'route' => 'program_show_42',
					'visible' => 0,
					'order' => 76,
				],
				[
					'id' => 'menuProgramShowWeb-39',
					'label' => 'Zpíváme a tančíme s Míšou',
					'route' => 'program_show_39',
					'visible' => 0,
					'order' => 77,
				],
				[
					'id' => 'menuProgramShowWeb-117',
					'label' => 'Energie a kraj',
					'route' => 'program_show_117',
					'visible' => 0,
					'order' => 78,
				],
				[
					'id' => 'menuProgramShowWeb-157',
					'label' => 'Moravskoslezská SESTRA 2025',
					'route' => 'program_show_157',
					'visible' => 0,
					'order' => 79,
				],
				[
					'id' => 'menuProgramShowWeb-169',
					'label' => 'Blízko vodě',
					'route' => 'program_show_169',
					'visible' => 0,
					'order' => 80,
				],
				[
					'id' => 'menuProgramShowWeb-159',
					'label' => 'Společenská odpovědnost 2024',
					'route' => 'program_show_159',
					'visible' => 0,
					'order' => 81,
				],
				[
					'id' => 'menuProgramShowWeb-156',
					'label' => 'Sportovec roku MS kraje 2024',
					'route' => 'program_show_156',
					'visible' => 0,
					'order' => 82,
				],
				[
					'id' => 'menuProgramShowWeb-132',
					'label' => 'Transformace kraje',
					'route' => 'program_show_132',
					'visible' => 0,
					'order' => 83,
				],
				[
					'id' => 'menuProgramShowWeb-79',
					'label' => 'Moravskoslezská SESTRA',
					'route' => 'program_show_79',
					'visible' => 0,
					'order' => 84,
				],
				[
					'id' => 'menuProgramShowWeb-151',
					'label' => 'Sportovní studio HOKEJ',
					'route' => 'program_show_151',
					'visible' => 0,
					'order' => 85,
				],
				[
					'id' => 'menuProgramShowWeb-122',
					'label' => 'Sportovec roku MS kraje 2023',
					'route' => 'program_show_122',
					'visible' => 0,
					'order' => 86,
				],
				[
					'id' => 'menuProgramShowWeb-91',
					'label' => 'Společenská odpovědnost',
					'route' => 'program_show_91',
					'visible' => 0,
					'order' => 87,
				],
				[
					'id' => 'menuProgramShowWeb-4',
					'label' => 'Jak šmakuje Moravskoslezsko?',
					'route' => 'program_show_4',
					'visible' => 0,
					'order' => 88,
				],
				[
					'id' => 'menuProgramShowWeb-10',
					'label' => 'Sběratelé',
					'route' => 'program_show_10',
					'visible' => 0,
					'order' => 90,
				],
				[
					'id' => 'menuProgramShowWeb-3',
					'label' => 'Kdo byl kdo',
					'route' => 'program_show_3',
					'visible' => 0,
					'order' => 93,
				],
				[
					'id' => 'menuProgramShowWeb-29',
					'label' => 'Nabídka práce',
					'route' => 'program_show_29',
					'visible' => 0,
					'order' => 95,
				],
				[
					'id' => 'menuProgramShowWeb-65',
					'label' => 'Starosti starostů',
					'route' => 'program_show_65',
					'visible' => 0,
					'order' => 107,
				],
				[
					'id' => 'menuProgramShowWeb-68',
					'label' => 'Legendy Moravskoslezského kraje',
					'route' => 'program_show_68',
					'visible' => 0,
					'order' => 108,
				],
				[
					'id' => 'menuProgramShowWeb-97',
					'label' => 'Sportovec roku MS kraje 2018',
					'route' => 'program_show_97',
					'visible' => 0,
					'order' => 109,
				],
				[
					'id' => 'menuProgramShowWeb-75',
					'label' => 'Žít normálně',
					'route' => 'program_show_75',
					'visible' => 0,
					'order' => 112,
				],
				[
					'id' => 'menuProgramShowWeb-81',
					'label' => 'Kutilové',
					'route' => 'program_show_81',
					'visible' => 0,
					'order' => 114,
				],
				[
					'id' => 'menuProgramShowWeb-99',
					'label' => 'FAN TV Revue',
					'route' => 'program_show_99',
					'visible' => 0,
					'order' => 117,
				],
				[
					'id' => 'menuProgramShowWeb-101',
					'label' => 'MISS Babča a Ostravský štramák',
					'route' => 'program_show_101',
					'visible' => 0,
					'order' => 118,
				],
				[
					'id' => 'menuProgramShowWeb-104',
					'label' => 'Sportovec roku MS kraje 2019',
					'route' => 'program_show_104',
					'visible' => 0,
					'order' => 119,
				],
				[
					'id' => 'menuProgramShowWeb-108',
					'label' => 'Vzpomínky na konec války',
					'route' => 'program_show_108',
					'visible' => 0,
					'order' => 120,
				],
				[
					'id' => 'menuProgramShowWeb-110',
					'label' => 'Diskuzní fórum',
					'route' => 'program_show_110',
					'visible' => 0,
					'order' => 121,
				],
				[
					'id' => 'menuProgramShowWeb-112',
					'label' => 'Dny NATO 2020',
					'route' => 'program_show_112',
					'visible' => 0,
					'order' => 122,
				],
				[
					'id' => 'menuProgramShowWeb-115',
					'label' => 'Vánoce s Permoníkem',
					'route' => 'program_show_115',
					'visible' => 0,
					'order' => 123,
				],
				[
					'id' => 'menuProgramShowWeb-116',
					'label' => 'Region pro sebe 2020',
					'route' => 'program_show_116',
					'visible' => 0,
					'order' => 124,
				],
				[
					'id' => 'menuProgramShowWeb-120',
					'label' => 'Sportovec dvacetiletí MS kraje 2000 - 2020',
					'route' => 'program_show_120',
					'visible' => 0,
					'order' => 125,
				],
				[
					'id' => 'menuProgramShowWeb-121',
					'label' => 'Poděkování zdravotníkům MSK',
					'route' => 'program_show_121',
					'visible' => 0,
					'order' => 126,
				],
				[
					'id' => 'menuProgramShowWeb-131',
					'label' => 'Svět z blízka',
					'route' => 'program_show_131',
					'visible' => 0,
					'order' => 127,
				],
				[
					'id' => 'menuProgramShowWeb-170',
					'label' => 'Šenovský miniexpres',
					'route' => 'program_show_170',
					'visible' => 0,
					'order' => 128,
				],
			],
		],
	],
];
